const horusHeresyDataBooks = [
{
	x: 100,
	y: 200,
	id: 1,
	title: "Horus Rising",
	author: "Dan Abnett",
	book:"Book 1",
	faction: ["Sons of horus"],
	pages:"320 (hardcover) 416 (softcover)",
	audio:"12h 16m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/horus-rising.html"
},
{
	x: 400,
	y: 200,
	id: 2,
	title: "False Gods",
	author: "Graham McNeill",
	book:"Book 2",
	faction: ["Sons of horus"],
	pages:"416",
	audio:"11h 20m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/False-Gods-eBook.html"
},
{
	x: 700,
	y: 200,
	id: 3,
	title: "Galaxy in Flames",
	author: "Ben Counter",
	book:"Book 3",
	faction: ["Sons of horus"],
	pages:"416",
	audio:"8h 51m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/galaxy-in-flames-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 4,
	title: "The Flight of the Eisenstein",
	author: "James Swallow",
	book:"Book 4",
	faction: ["Sons of horus","Knight Errant"],
	pages:"416",
	audio:"12h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/flight-of-the-eisenstein-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 5,
	title: "Fulgrim",
	author: "Graham McNeill",
	book:"Book 5",
	faction: ["Emperor's Children"],
	pages:"512",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/fulgrim-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 6,
	title: "Descent of Angels",
	author: "Mitchel Scanlon",
	book:"Book 6",
	faction: ["Dark Angels"],
	pages:"416",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/descent-of-angels-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 7,
	title: "Legion",
	author: "Dan Abnett",
	book:"Book 7",
	faction: ["Alpha Legion","Perpetuals"],
	pages:"416",
	audio:"11h",
	rating: "%",
	link:"https://www.blacklibrary.com/all-products/legion-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 8,
	title: "Battle for the Abyss",
	author: "Ben Counter",
	book:"Book 8",
	faction: [""],
	pages:"416",
	audio:"10h 42m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/battle-for-the-abyss-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 9,
	title: "Mechanicum",
	author: "Graham McNeill",
	book:"Book 9",
	faction: ["Mechanicum"],
	pages:"416",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/Mechanicum-eBook.html"
},
{
	x: 1,
	y: 1,
	id: 10,
	title: "Tales of Heresy",
	author: "Dan Abnett",
	book:"Book 10 Anthology",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/Tales-of-Heresy-eBook.html"
},
{
	x: 1,
	y: 1,
	id: 11,
	title: "Fallen Angels",
	author: "Mike Lee",
	book:"Book 11",
	faction: [""],
	pages:"416",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/fallen-angels-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 12,
	title: "A Thousand Sons",
	author: "Graham McNeill",
	book:"Book 12",
	faction: [""],
	pages:"416",
	audio:"16h",
	rating: "%",
	link:"http://www.blacklibrary.com/Blog/graham-mcneill-becomes-new-york-times-best-selling-author.html"
},
{
	x: 1,
	y: 1,
	id: 13,
	title: "Nemesis",
	author: "James Swallow",
	book:"Book 13",
	faction: [""],
	pages:"507",
	audio:"15h",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 14,
	title: "The First Heretic",
	author: "Aaron Dembski-Bowden",
	book:"Book 14",
	faction: [""],
	pages:"502",
	audio:"14h 20m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/First-heretic-the-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 15,
	title: "Prospero Burns",
	author: "Dan Abnett",
	book:"Book 15",
	faction: [""],
	pages:"416",
	audio:"15h",
	rating: "%",
	link:"http://www.blacklibrary.com/Blog/A-look-into-the-future.html"
},
{
	x: 1,
	y: 1,
	id: 16,
	title: "Age of Darkness",
	author: "Dan Abnett",
	book:"Book 16 Anthology",
	faction: [""],
	pages:"408",
	audio:"12h 30m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/age-of-darkness.html"
},
{
	x: 1,
	y: 1,
	id: 17,
	title: "The Outcast Dead",
	author: "Graham McNeill",
	book:"Book 17",
	faction: [""],
	pages:"416",
	audio:"14h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-outcast-dead-ebook-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 18,
	title: "Deliverance Lost",
	author: "Gav Thorpe",
	book:"Book 18",
	faction: [""],
	pages:"480",
	audio:"16h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/deliverance-lost-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 19,
	title: "Know No Fear",
	author: "Dan Abnett",
	book:"Book 19",
	faction: [""],
	pages:"416",
	audio:"11h",
	rating: "%",
	link:"http://www.blacklibrary.com/Blog/Questions-for-the-High-Lords_.html"
},
{
	x: 1,
	y: 1,
	id: 20,
	title: "The Primarchs",
	author: "Nick Kyme",
	book:"Book 20 Anthology",
	faction: [""],
	pages:"416",
	audio:"13h 30m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-primarchs-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 21,
	title: "Fear to Tread",
	author: "James Swallow",
	book:"Book 21",
	faction: [""],
	pages:"516",
	audio:"15h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/fear-to-tread-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 22,
	title: "Shadows of Treachery",
	author: "Dan Abnett",
	book:"Book 22 Anthology",
	faction: [""],
	pages:"416",
	audio:"11h 44m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/shadows-of-treachery-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 23,
	title: "Angel Exterminatus",
	author: "Graham McNeill",
	book:"Book 23",
	faction: [""],
	pages:"448",
	audio:"19h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/angel-exterminatus-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 24,
	title: "Betrayer",
	author: "Aaron Dembski-Bowden",
	book:"Book 24",
	faction: [""],
	pages:"416",
	audio:"14h 9m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/betrayer-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 25,
	title: "Mark of Calth",
	author: "Dan Abnett",
	book:"Book 25 Anthology",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/mark-of-calth-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 26,
	title: "Vulkan Lives",
	author: "Nick Kyme",
	book:"Book 26",
	faction: [""],
	pages:"416",
	audio:"13h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/vulkan-lives-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 27,
	title: "The Unremembered Empire",
	author: "Dan Abnett",
	book:"Book 27",
	faction: [""],
	pages:"416",
	audio:"13h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-unremembered-empire-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 28,
	title: "Scars",
	author: "Chris Wraight",
	book:"Book 28",
	faction: [""],
	pages:"416",
	audio:"11h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/scars-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 29,
	title: "Vengeful Spirit ",
	author: "Graham McNeill",
	book:"Book 29",
	faction: [""],
	pages:"544",
	audio:"15h",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 30,
	title: "The Damnation of Pythos",
	author: "David Annandale",
	book:"Book 30",
	faction: [""],
	pages:"416",
	audio:"12h",
	rating: "%",
	link:"http://www.blacklibrary.com/Blog/new-hh-art.html"
},
{
	x: 1,
	y: 1,
	id: 31,
	title: "Legacies of Betrayal",
	author: "Aaron Dembski-Bowden",
	book:"Book 31 Anthology",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 32,
	title: "Deathfire",
	author: "Nick Kyme",
	book:"Book 32",
	faction: [""],
	pages:"416",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/deathfire-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 33,
	title: "War Without End",
	author: "Aaron Dembski-Bowden",
	book:"Book 33 Anthology",
	faction: [""],
	pages:"624",
	audio:"16h 11m",
	rating: "%",
	link:"https://www.blacklibrary.com/all-products/hh-war-without-end-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 34,
	title: "Pharos",
	author: "Guy Haley",
	book:"Book 34",
	faction: [""],
	pages:"480",
	audio:"13h 23m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/pharos-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 35,
	title: "Eye of Terra",
	author: "Aaron Dembski-Bowden Anthology",
	book:"Book 35",
	faction: [""],
	pages:"480",
	audio:"12h 18m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 36,
	title: "The Path of Heaven",
	author: "Chris Wraight",
	book:"Book 36",
	faction: [""],
	pages:"432",
	audio:"13h 28m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/path-of-heaven-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 37,
	title: "The Silent War",
	author: "",
	book:"Book 37 Anthology",
	faction: [""],
	pages:"480",
	audio:"14h 2m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-silent-war-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 38,
	title: "Angels of Caliban",
	author: "Gav Thorpe",
	book:"Book 38",
	faction: [""],
	pages:"480",
	audio:"10h 57m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 39,
	title: "Praetorian of Dorn",
	author: "John French",
	book:"Book 39",
	faction: [""],
	pages:"478",
	audio:"12h 57m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-praetorian-of-dorn-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 40,
	title: "Corax",
	author: "Gav Thorpe",
	book:"Book 40 Anthology",
	faction: [""],
	pages:"464",
	audio:"12h 49m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/corax-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 41,
	title: "The Master of Mankind",
	author: "Aaron Dembski-Bowden",
	book:"Book 41",
	faction: [""],
	pages:"448",
	audio:"12h 34m",
	rating: "%",
	link:"https://aarondembskibowden.wordpress.com/2015/08/28/okay-okay-fine-this-is-what-im-writing/"
},
{
	x: 1,
	y: 1,
	id: 42,
	title: "Garro",
	author: "James Swallow",
	book:"Book 42 Anthology",
	faction: [""],
	pages:"384",
	audio:"12h 27m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-garro-weapon-of-fate-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 43,
	title: "Shattered Legions",
	author: "Dan Abnett",
	book:"Book 43 Anthology",
	faction: [""],
	pages:"496",
	audio:"13h 14m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 44,
	title: "The Crimson King",
	author: "Graham McNeill",
	book:"Book 44",
	faction: [""],
	pages:"456",
	audio:"14h 46m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-the-crimson-king-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 45,
	title: "Tallarn",
	author: "John French",
	book:"Book 45 Anthology",
	faction: [""],
	pages:"480",
	audio:"12h 54m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 46,
	title: "Ruinstorm",
	author: "David Annandale",
	book:"Book 46",
	faction: [""],
	pages:"480",
	audio:"10h 7m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 47,
	title: "Old Earth",
	author: "Nick Kyme",
	book:"Book 47",
	faction: [""],
	pages:"400",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/old-earth-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 48,
	title: "The Burden of Loyalty",
	author: "",
	book:"Book 48 Anthology",
	faction: [""],
	pages:"496",
	audio:"13h 44m",
	rating: "%",
	link:"https://www.blacklibrary.com/all-products/the-burden-of-loyalty-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 49,
	title: "Wolfsbane",
	author: "Guy Haley",
	book:"Book 49",
	faction: [""],
	pages:"400",
	audio:"11h 36m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/wolfsbane-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 50,
	title: "Born of Flame",
	author: "Nick Kyme",
	book:"Book 50 Anthology",
	faction: [""],
	pages:"544",
	audio:"15h 54m",
	rating: "%",
	link:"https://www.blacklibrary.com/prod-home/new-paperback/born-of-flame-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 51,
	title: "Slaves to Darkness",
	author: "John French",
	book:"Book 51",
	faction: [""],
	pages:"432",
	audio:"10h 49m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 52,
	title: "Heralds of the Siege",
	author: "",
	book:"Book 52 Anthology",
	faction: [""],
	pages:"432",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 53,
	title: "Titandeath",
	author: "Guy Haley",
	book:"Book 53",
	faction: [""],
	pages:"480",
	audio:"13h and 40 Minutes",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 54,
	title: "The Buried Dagger",
	author: "James Swallow",
	book:"Book 54",
	faction: [""],
	pages:"400",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 55,
	title: "The Solar War",
	author: "John French",
	book:"Siege of Terra",
	faction: [""],
	pages:"384",
	audio:"12h 14m",
	rating: "%",
	link:"https://www.blacklibrary.com/coming-soon/may/siege-of-terra-the-solar-war-ebook-2019.html"
},
{
	x: 1,
	y: 1,
	id: 56,
	title: "The Lost and the Damned",
	author: "Guy Haley",
	book:"Siege of Terra",
	faction: [""],
	pages:"416",
	audio:"13h 2m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 57,
	title: "The First Wall",
	author: "Gav Thorpe",
	book:"Siege of Terra",
	faction: [""],
	pages:"460",
	audio:"12h 44m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 58,
	title: "Sons of the Selenar",
	author: "Graham McNeill",
	book:"Siege of Terra",
	faction: [""],
	pages:"192",
	audio:"4h 23m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 59,
	title: "Saturnine",
	author: "Dan Abnett",
	book:"Siege of Terra",
	faction: [""],
	pages:"464",
	audio:"16h 48m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 60,
	title: "The Fury of Magnus",
	author: "Graham McNeill",
	book:"Siege of Terra",
	faction: [""],
	pages:"6h 44m",
	audio:"226",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 61,
	title: "Mortis",
	author: "John French",
	book:"Siege of Terra",
	faction: [""],
	pages:"560",
	audio:"16h 26m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 62,
	title: "Warhawk",
	author: "Chris Wraight",
	book:"Siege of Terra",
	faction: [""],
	pages:"482",
	audio:"14h 15m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 63,
	title: "Roboute Guilliman: Lord of Ultramar",
	author: "David Annandale",
	book:"The Primarchs",
	faction: [""],
	pages:"240",
	audio:"4h 58m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 64,
	title: "Leman Russ: The Great Wolf",
	author: "Chris Wraight",
	book:"The Primarchs",
	faction: [""],
	pages:"240",
	audio:"6h 4m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 65,
	title: "Thousand Sons",
	author: "Graham McNeill",
	book:"The Primarchs",
	faction: [""],
	pages:"201",
	audio:"5h 45m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/magnus-the-red.html"
},
{
	x: 1,
	y: 1,
	id: 66,
	title: "Perturabo: The Hammer of Olympia",
	author: "Guy Haley",
	book:"The Primarchs",
	faction: [""],
	pages:"240",
	audio:"6h 49m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 67,
	title: "Lorgar: Bearer of the Word",
	author: "Gav Thorpe",
	book:"The Primarchs",
	faction: [""],
	pages:"208",
	audio:"6h 37m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 68,
	title: "Fulgrim: The Palatine Phoenix",
	author: "Josh Reynolds",
	book:"The Primarchs",
	faction: [""],
	pages:"224",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/fulgrim-the-palatine-phoenix-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 69,
	title: "Ferrus Manus: Gorgon of Medusa",
	author: "David Guymer",
	book:"The Primarchs",
	faction: [""],
	pages:"224",
	audio:"6h 15m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/ferrus-manus-gorgon-of-medusa-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 70,
	title: "Jaghatai Khan: Warhawk of Chogoris",
	author: "Chris Wraight",
	book:"The Primarchs",
	faction: [""],
	pages:"224",
	audio:"6h 9 Minutes",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 71,
	title: "Vulkan: Lord of Drakes",
	author: "David Annandale",
	book:"The Primarchs",
	faction: [""],
	pages:"224",
	audio:"4h 50m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 72,
	title: "Sons of the Emperor",
	author: "",
	book:"The Primarchs Anthology",
	faction: [""],
	pages:"254",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 73,
	title: "Raven Guard",
	author: "Guy Haley",
	book:"The Primarchs",
	faction: [""],
	pages:"224",
	audio:"6h 32m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 74,
	title: "Angron: Slave of Nuceria",
	author: "Ian St. Martin",
	book:"The Primarchs",
	faction: [""],
	pages:"224",
	audio:"6h 1m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 75,
	title: "Scions of the Emperor",
	author: "",
	book:"The Primarchs Anthology",
	faction: [""],
	pages:"182",
	audio:"",
	rating: "%",
	link:"https://www.goodreads.com/book/show/43886241-scions-of-the-emperor?ac=1&from_search=true"
},
{
	x: 1,
	y: 1,
	id: 76,
	title: "Night Lords",
	author: "Guy Haley",
	book:"The Primarchs",
	faction: [""],
	pages:"280",
	audio:"6h 5m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 77,
	title: "Lion El'Jonson: Lord of the First",
	author: "David Guymer",
	book:"The Primarchs",
	faction: [""],
	pages:"320",
	audio:"5h 55m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 78,
	title: "Alpharius: Head of the Hydra",
	author: "Mike Brooks",
	book:"The Primarchs",
	faction: [""],
	pages:"202",
	audio:"5h 23m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 79,
	title: "Blood of the Emperor",
	author: "",
	book:"The Primarchs",
	faction: [""],
	pages:"192",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 80,
	title: "Grandfather's Gift",
	author: "Guy Haley",
	book:"Short Stories",
	faction: [""],
	pages:"17",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 81,
	title: "The Atonement of Fire",
	author: "David Annandale",
	book:"Short Stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 82,
	title: "A Lesson in Iron",
	author: "David Guymer",
	book:"Short Stories",
	faction: [""],
	pages:"21",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 83,
	title: "Ghost of Nuceria",
	author: "Ian St. Martin",
	book:"Short Stories",
	faction: [""],
	pages:"21",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 84,
	title: "The Passing of Angels",
	author: "John French",
	book:"Short Stories",
	faction: [""],
	pages:"21",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 85,
	title: "The Abyssal Edge",
	author: "Aaron Dembski-Bowden",
	book:"Short Stories",
	faction: [""],
	pages:"30",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 86,
	title: "Mercy of the Dragon",
	author: "Nick Kyme",
	book:"Short Stories",
	faction: [""],
	pages:"41",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 87,
	title: "Will of the Legion",
	author: "Andy Clark",
	book:"Short Stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 88,
	title: "Embers of Extinction",
	author: "Brandon Easton",
	book:"Short Stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 89,
	title: "Perturabo: Stone and Iron",
	author: "Robbie MacNiven",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"21 Minutes",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 90,
	title: "Malcador: First Lord of the Imperium",
	author: "L.J. Goulding",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"25 Minutes",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 91,
	title: "Konrad Curze: A Lesson in Darkness",
	author: "Ian St. Martin",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"27 Minutes",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 92,
	title: "The Lords of Terra",
	author: "L.J. Goulding",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"1 hour 13m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 93,
	title: "Illyrium",
	author: "Darius Hinks",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"28m",
	rating: "%",
	link:"https://www.blacklibrary.com/prod-home/advent-home/illyrium-2019.html"
},
{
	x: 1,
	y: 1,
	id: 94,
	title: "The Revelation of the Horus",
	author: "David Annandale",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"24m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 95,
	title: "Morningstar",
	author: "Graham McNeill",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"24m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 96,
	title: "Valdor: Birth of the Imperium",
	author: "Chris Wraight",
	book:"Horus Heresy Characters Novels",
	faction: [""],
	pages:"272",
	audio:"6h 16m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 97,
	title: "Luther: First of the Fallen",
	author: "Gav Thorpe",
	book:"Horus Heresy Characters Novels",
	faction: [""],
	pages:"224",
	audio:"7h 32m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 98,
	title: "Sigismund: The Eternal Crusader",
	author: "John French",
	book:"Horus Heresy Characters Novels",
	faction: [""],
	pages:"192",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 99,
	title: "Promethean Sun",
	author: "Nick Kyme",
	book:"Official Novellas",
	faction: ["4h 5m"],
	pages:"128",
	audio:"4h 5m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/promethean-sun-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 100,
	title: "Aurelian",
	author: "Aaron Dembski-Bowden",
	book:"Official Novellas",
	faction: [""],
	pages:"128",
	audio:"3h 16m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/aurelian-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 101,
	title: "Brotherhood of the Storm",
	author: "Chris Wraight",
	book:"Official Novellas",
	faction: [""],
	pages:"103",
	audio:"4h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/brotherhood-of-the-storm-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 102,
	title: "The Reflection Crack'd",
	author: "Graham McNeill",
	book:"Official Novellas",
	faction: [""],
	pages:"95",
	audio:"3h 38m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-reflection-crackd-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 103,
	title: "Feat of Iron",
	author: "Nick Kyme",
	book:"Official Novellas",
	faction: [""],
	pages:"102",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/feat-of-iron-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 104,
	title: "The Lion",
	author: "Gav Thorpe",
	book:"Official Novellas",
	faction: [""],
	pages:"95",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-lion-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 105,
	title: "The Serpent Beneath",
	author: "Rob Sanders",
	book:"Official Novellas",
	faction: [""],
	pages:"101",
	audio:"3h 43m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-serpent-beneath-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 106,
	title: "Corax: Soulforge",
	author: "Gav Thorpe",
	book:"Official Novellas",
	faction: [""],
	pages:"128",
	audio:"3h 25m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/corax-soulforge-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 107,
	title: "Scorched Earth",
	author: "Nick Kyme",
	book:"Official Novellas",
	faction: [""],
	pages:"92",
	audio:"3h 50m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/scorched-earth-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 108,
	title: "Tallarn: Executioner",
	author: "John French",
	book:"Official Novellas",
	faction: [""],
	pages:"123",
	audio:"3h 58m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/tallarn-executioner-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 109,
	title: "Prince of Crows",
	author: "Aaron Dembski-Bowden",
	book:"Official Novellas",
	faction: [""],
	pages:"99",
	audio:"3h 20m",
	rating: "%",
	link:"https://web.archive.org/web/20170402224633/https://www.blacklibrary.com/the-horus-heresy/novels/prince-of-crows-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 110,
	title: "Crimson Fist",
	author: "John French",
	book:"Official Novellas",
	faction: [""],
	pages:"93",
	audio:"3h",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-crimson-fist-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 111,
	title: "The Purge",
	author: "Anthony Reynolds",
	book:"Official Novellas",
	faction: [""],
	pages:"114",
	audio:"3h 40m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-purge-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 112,
	title: "Ravenlord",
	author: "Gav Thorpe",
	book:"Official Novellas",
	faction: [""],
	pages:"112",
	audio:"3h 40m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/ravenlord-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 113,
	title: "The Seventh Serpent",
	author: "Graham McNeill",
	book:"Official Novellas",
	faction: [""],
	pages:"132",
	audio:"4h 27m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-seventh-serpent-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 114,
	title: "Tallarn: Ironclad",
	author: "John French",
	book:"Official Novellas",
	faction: [""],
	pages:"240",
	audio:"7h 26m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/tallarn-ironclad-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 115,
	title: "Cybernetica",
	author: "Rob Sanders",
	book:"Official Novellas",
	faction: [""],
	pages:"134",
	audio:"5h 11m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/cybernetica-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 116,
	title: "Wolf King",
	author: "Chris Wraight",
	book:"Official Novellas",
	faction: [""],
	pages:"114",
	audio:"3h 54m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/wolf-king-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 117,
	title: "The Honoured",
	author: "Rob Sanders",
	book:"Official Novellas",
	faction: [""],
	pages:"240",
	audio:"5h 37m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-honoured-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 118,
	title: "The Unburdened",
	author: "David Annandale",
	book:"Official Novellas",
	faction: [""],
	pages:"192",
	audio:"5h 48m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-unburdened-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 119,
	title: "Garro: Vow of Faith",
	author: "James Swallow",
	book:"Official Novellas",
	faction: [""],
	pages:"126",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/garro-vow-of-faith-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 120,
	title: "Sons of the Forge",
	author: "Nick Kyme",
	book:"Official Novellas",
	faction: [""],
	pages:"204",
	audio:"6h 38m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/novels/sons-of-the-forge-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 121,
	title: "Dreadwing",
	author: "David Guymer",
	book:"Official Novellas",
	faction: [""],
	pages:"114",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/series/novella-series-1/dreadwing-ebook-2018.html"
},
{
	x: 1,
	y: 1,
	id: 122,
	title: "Spear of Ultramar",
	author: "David Annandale",
	book:"Official Novellas",
	faction: [""],
	pages:"100",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/new-titles/featured/spear-of-ultramar-ebook-2018.html"
},
{
	x: 1,
	y: 1,
	id: 123,
	title: "Angron",
	author: "Aaron Dembski-Bowden",
	book:"Collections Anthology",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/angron-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 124,
	title: "The Imperial Truth",
	author: "",
	book:"Collections Anthology",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-imperial-truth-ebook-collection.html"
},
{
	x: 1,
	y: 1,
	id: 125,
	title: "Sedition's Gate",
	author: "Nick Kyme",
	book:"Collections Anthology",
	faction: [""],
	pages:"142",
	audio:"",
	rating: "%",
	link:"http://www.blacklibrary.com/new-at-bl/Horus_Heresy_Weekender_and_New_Night_Lords_Art.html"
},
{
	x: 1,
	y: 1,
	id: 126,
	title: "Echoes of Ruin",
	author: "David Annandale",
	book:"Collections Anthology",
	faction: [""],
	pages:"",
	audio:"75m",
	rating: "%",
	link:"https://www.blacklibrary.com/all-products/echoes-of-ruin.html"
},
{
	x: 1,
	y: 1,
	id: 127,
	title: "Death and Defiance",
	author: "Aaron Dembski-Bowden",
	book:"Collections Anthology",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/death-and-defiance-ebook-collection.html"
},
{
	x: 1,
	y: 1,
	id: 128,
	title: "Blades of the Traitor",
	author: "John French",
	book:"Collections Anthology",
	faction: [""],
	pages:"118",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 129,
	title: "Meduson",
	author: "Dan Abnett",
	book:"Collections Anthology",
	faction: [""],
	pages:"279",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 130,
	title: "Betrayal at Calth",
	author: "David Annandale",
	book:"Collections Anthology",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 131,
	title: "Echoes of the Imperium",
	author: "",
	book:"Collections Anthology",
	faction: [""],
	pages:"",
	audio:"74m",
	rating: "%",
	link:"http://www.blacklibrary.com/all-products/echoes-of-imperium-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 132,
	title: "Virtue of the Sons/Sins of the Father",
	author: "Andy Smillie",
	book:"Collections Anthology",
	faction: [""],
	pages:"",
	audio:"50m",
	rating: "%",
	link:"http://www.blacklibrary.com/all-products/virtues-sons-sins-father-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 133,
	title: "Echoes of Revelation",
	author: "Dan Abnett",
	book:"Collections Anthology",
	faction: [""],
	pages:"",
	audio:"75m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/hh-echoes-of-revelation-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 134,
	title: "The Lightning Tower",
	author: "Dan Abnett",
	book:"Short stories",
	faction: [""],
	pages:"20",
	audio:"40m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/lightning-tower-enhanced-audio.html"
},
{
	x: 1,
	y: 1,
	id: 135,
	title: "The Dark King",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"39",
	audio:"36m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/dark-king-enhanced-audio.html"
},
{
	x: 1,
	y: 1,
	id: 136,
	title: "Blood Games",
	author: "Dan Abnett",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1 hour 27m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/blood-games-eshort.html"
},
{
	x: 1,
	y: 1,
	id: 137,
	title: "Wolf at the Door",
	author: "Mike Lee",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"2h 54m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/wolf-at-the-door-audio.html"
},
{
	x: 1,
	y: 1,
	id: 138,
	title: "Scions of the Storm",
	author: "Anthony Reynolds",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1 hour 18m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/scions-of-the-storm-audio.html"
},
{
	x: 1,
	y: 1,
	id: 139,
	title: "The Voice",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"2h 2m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/the-voice-audio.html"
},
{
	x: 1,
	y: 1,
	id: 140,
	title: "Call of the Lion",
	author: "Gav Thorpe",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1 hour 16m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/call-of-the-lion-audio.html"
},
{
	x: 1,
	y: 1,
	id: 141,
	title: "The Last Church",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1 hour 29m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/the-last-church-audio.html"
},
{
	x: 1,
	y: 1,
	id: 142,
	title: "After Desh'ea",
	author: "Matthew Farrer",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1 hour 7m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/after-deshea-audio.html"
},
{
	x: 1,
	y: 1,
	id: 143,
	title: "Rules of Engagement",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1h 36m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/rules-of-engagement-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 144,
	title: "Liar's Due",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1h 33m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/liars-due-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 145,
	title: "Forgotten Sons",
	author: "Nick Kyme",
	book:"Short stories",
	faction: [""],
	pages:"1h 54m",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/forgotten-sons-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 146,
	title: "The Last Remembrancer",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"54m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/last-remembrancer-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 147,
	title: "Rebirth",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1h 21m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/horus-heresy-rebirth-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 148,
	title: "The Face of Treachery",
	author: "Gav Thorpe",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"52m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/face-of-treachery-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 149,
	title: "Little Horus",
	author: "Dan Abnett",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"56m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/little-horus-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 150,
	title: "The Iron Within",
	author: "Rob Sanders",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1h 53m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/iron-within-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 151,
	title: "Savage Weapons",
	author: "Aaron Dembski-Bowden",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1h 27m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/savage-weapons-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 152,
	title: "Army of One",
	author: "Rob Sanders",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"8m",
	rating: "%",
	link:"http://www.blacklibrary.com/all-products/army-of-one-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 153,
	title: "Kryptos",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"40m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 154,
	title: "Distant Echoes of Old Night",
	author: "Rob Sanders",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"53m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 155,
	title: "Lost Sons",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"42m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/lost_sons.html"
},
{
	x: 1,
	y: 1,
	id: 156,
	title: "Death of a Silversmith",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"30m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/death_of_a_silversmith.html"
},
{
	x: 1,
	y: 1,
	id: 157,
	title: "The Divine Word",
	author: "Gav Thorpe",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"43m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 158,
	title: "The Kaban Project",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1h 39m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 159,
	title: "The Gates of Terra",
	author: "Nick Kyme",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"40m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 160,
	title: "Lord of the Red Sands",
	author: "Aaron Dembski-Bowden",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"11m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/lord-of-the-red-sands-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 161,
	title: "Serpent",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"12m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/serpent-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 162,
	title: "Luna Mendax",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"38m",
	rating: "%",
	link:"https://www.blacklibrary.com/all-products/luna-mendax-eshort.html"
},
{
	x: 1,
	y: 1,
	id: 163,
	title: "Riven",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1 hour 25m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/riven-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 164,
	title: "Lone Wolf",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"11m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/advent-day-one-bjorn-lone-wolf-eBook.html"
},
{
	x: 1,
	y: 1,
	id: 165,
	title: "The Wolf of Ash and Fire",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1h 17m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 166,
	title: "Heart of the Conqueror",
	author: "Aaron Dembski-Bowden",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"12m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/heart-of-the-conquerer-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 167,
	title: "Child of Night",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"38m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/child-of-night-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 168,
	title: "The Devine Adoratrice",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1h 54m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-devine-adoratrice-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 169,
	title: "Daemonology",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"46m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/daemonology-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 170,
	title: "Sins of the Father",
	author: "Andy Smillie",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"13m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/sins-of-the-father-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 171,
	title: "The Final Compliance of Sixty-Three Fourteen",
	author: "Guy Haley",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"18m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/final-compliance-of-63-14-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 172,
	title: "Vorax",
	author: "Matthew Farrer",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"15m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/vorax-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 173,
	title: "The Value of Fear",
	author: "Gav Thorpe",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"15m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/value-of-fear-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 174,
	title: "Brotherhood of the Moon",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"18m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/brotherhood-of-the-moon-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 175,
	title: "Virtues of the Sons",
	author: "Andy Smillie",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"37m",
	rating: "%",
	link:"https://www.blacklibrary.com/all-products/virtues-sons-sins-father-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 176,
	title: "Imperfect",
	author: "Nick Kyme",
	book:"Short stories",
	faction: [""],
	pages:"34m",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/imperfect-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 177,
	title: "Howl of the Hearthworld",
	author: "Aaron Dembski-Bowden",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/howl-of-the-hearthworld-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 178,
	title: "A Safe and Shadowed Place",
	author: "Guy Haley",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/safe-and-shadowed-place-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 179,
	title: "Gunsight",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/gunsight-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 180,
	title: "Black Oculus",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"10m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/black-oculus-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 181,
	title: "Wolf Mother",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1 hour 12m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 182,
	title: "Twisted",
	author: "Guy Haley",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"1 hour 18m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 183,
	title: "Chirurgeon",
	author: "Nick Kyme",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"45m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 184,
	title: "Tallarn: Witness",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 185,
	title: "Ironfire",
	author: "Rob Sanders",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 186,
	title: "Hands of the Emperor",
	author: "Rob Sanders",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 187,
	title: "By the Lion's Command",
	author: "Gav Thorpe",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 188,
	title: "All That Remains",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 189,
	title: "The Phoenician",
	author: "Nick Kyme",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 190,
	title: "Artefacts",
	author: "Nick Kyme",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 191,
	title: "Ghosts Speak Not",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/ghosts-speak-not-patience-eshort.html"
},
{
	x: 1,
	y: 1,
	id: 192,
	title: "Patience",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/ghosts-speak-not-patience-eshort.html"
},
{
	x: 1,
	y: 1,
	id: 193,
	title: "Tallarn: Siren",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 194,
	title: "Inheritor",
	author: "Gav Thorpe",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/hh-inheritor-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 195,
	title: "other uses",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 196,
	title: "Myriad",
	author: "Rob Sanders",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/all-products/myriad.html"
},
{
	x: 1,
	y: 1,
	id: 197,
	title: "Into Exile",
	author: "Aaron Dembski-Bowden",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/into-exile-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 198,
	title: "The Grey Raven",
	author: "Gav Thorpe",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-grey-raven-ebook.html"
},
{
	x: 1,
	y: 1,
	id: 199,
	title: "",
	author: "Guy Haley",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 200,
	title: "Exocytosis",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 201,
	title: "The Last Son of Prospero",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 202,
	title: "Titan Legion",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 203,
	title: "Titan Legion also known as the Ember Wolves",
	author: "Rob Sanders",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 204,
	title: "Restorer",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 205,
	title: "The Laurel of Defiance",
	author: "Guy Haley",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 206,
	title: "Immortal Duty",
	author: "Nick Kyme",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 207,
	title: "A Lesson in Iron",
	author: "David Guymer",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 208,
	title: "The Atonement of Fire",
	author: "David Annandale",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 209,
	title: "Duty Waits",
	author: "Guy Haley",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 210,
	title: "Magisterium",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 211,
	title: "Now Peals Midnight",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 212,
	title: "Dreams of Unity",
	author: "Nick Kyme",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/dreams-of-unity-eshort.html"
},
{
	x: 1,
	y: 1,
	id: 213,
	title: "The Board is Set",
	author: "Gav Thorpe",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 214,
	title: "Imperial Fists",
	author: "John French",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 215,
	title: "Word Bearers",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 216,
	title: "Massacre",
	author: "Aaron Dembski-Bowden",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 217,
	title: "Two Metaphysical Blades",
	author: "Chris Wraight",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 218,
	title: "Prologue to Nikaea",
	author: "David Annandale",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 219,
	title: "Old Wounds, New Scars",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 220,
	title: "Abyssal",
	author: "David Annandale",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 221,
	title: "The Last Council",
	author: "L.J. Goulding",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 222,
	title: "A Rose Watered with Blood",
	author: "Aaron Dembski-Bowden",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/prod-home/advent-2018/advent-2018-24-rose-watered-blood-eshort.html"
},
{
	x: 1,
	y: 1,
	id: 223,
	title: "Space Marines Portal",
	author: "Aaron Dembski-Bowden",
	book:"Short stories",
	faction: [""],
	pages:"20",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 224,
	title: "Death Guard",
	author: "James Swallow",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 225,
	title: "The Serpent's Dance",
	author: "Mike Brooks",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 226,
	title: "The Lightning Hall",
	author: "Graham McNeill",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 227,
	title: "Eater of Dreams",
	author: "Marc Collins",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 228,
	title: "Bloodhowl",
	author: "Chris Forrester",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 229,
	title: "Amor Fati",
	author: "Michael F. Haspil",
	book:"Short stories",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 230,
	title: "Crusade's End",
	author: "Dan Abnett",
	book:"Omnibus Editions",
	faction: [""],
	pages:"1024",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 231,
	title: "The Razing of Prospero",
	author: "Dan Abnett",
	book:"Omnibus Editions",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 232,
	title: "The Last Phoenix",
	author: "John French",
	book:"Omnibus Editions",
	faction: [""],
	pages:"1024",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 233,
	title: "The Dark King and The Lightning Tower",
	author: "Graham McNeill",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"1 hour 16m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/Dark-King-and-The-Lightning-Tower-Audiobook-The-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 234,
	title: "Raven's Flight",
	author: "Gav Thorpe",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"75 Minutes",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 235,
	title: "Garro: Oath of Moment",
	author: "James Swallow",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"71m",
	rating: "%",
	link:"https://www.blacklibrary.com/series/garro/Garro-oath-of-moment-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 236,
	title: "Garro: Legion of One",
	author: "James Swallow",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"68m",
	rating: "%",
	link:"https://www.blacklibrary.com/series/garro/garro-legion-of-one-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 237,
	title: "surgical procedure",
	author: "Aaron Dembski-Bowden",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"1 hour 13m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 238,
	title: "Grey Angel",
	author: "John French",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"35 Minutes",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 239,
	title: "Burden of Duty",
	author: "James Swallow",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/series/garro/burden-of-duty-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 240,
	title: "Garro: Sword of Truth",
	author: "James Swallow",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"140m",
	rating: "%",
	link:"https://www.blacklibrary.com/series/garro/garro-sword-of-truth-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 241,
	title: "the audio book by John French",
	author: "John French",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"9m",
	rating: "%",
	link:"https://www.blacklibrary.com/all-products/warmaster-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 242,
	title: "Strike and Fade",
	author: "Guy Haley",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"10m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 243,
	title: "Veritas Ferrum",
	author: "David Annandale",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 244,
	title: "other uses",
	author: "Chris Wraight",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"75 min",
	rating: "%",
	link:"http://www.blacklibrary.com/Blog/you-sigillite-horus-heresy-art.html"
},
{
	x: 1,
	y: 1,
	id: 245,
	title: "Honour to the Dead",
	author: "Gav Thorpe",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"75m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/Honour-to-the-Dead.html"
},
{
	x: 1,
	y: 1,
	id: 246,
	title: "Wolf Hunt",
	author: "Graham McNeill",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"80m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 247,
	title: "Censure",
	author: "Nick Kyme",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"75m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/censure-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 248,
	title: "Thief of Revelations",
	author: "Graham McNeill",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"35m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/thief-of-revelations-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 249,
	title: "Khârn: The Eightfold Path",
	author: "Anthony Reynolds",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"12m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 250,
	title: "Lucius: The Eternal Blademaster",
	author: "Graham McNeill",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"12m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/advent-day-twenty-one-lucius-the-eternal-blade.html"
},
{
	x: 1,
	y: 1,
	id: 251,
	title: "Cypher: Guardian of Order",
	author: "Gav Thorpe",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"12m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 252,
	title: "Hunter's Moon",
	author: "Guy Haley",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"35 min",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/hunters-moon-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 253,
	title: "Wolf's Claw",
	author: "Chris Wraight",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"10m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 254,
	title: "the audio drama",
	author: "John French",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"65m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/templar-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 255,
	title: "Garro: Shield of Lies",
	author: "James Swallow",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"130m",
	rating: "%",
	link:"https://www.blacklibrary.com/series/garro/garro-shield-of-lies-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 256,
	title: "Master of the First",
	author: "Gav Thorpe",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"36m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 257,
	title: "The Long Night",
	author: "Aaron Dembski-Bowden",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"42m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 258,
	title: "Stratagem",
	author: "Nick Kyme",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"21m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 259,
	title: "title",
	author: "Andy Smillie",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"20m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 260,
	title: "The Watcher",
	author: "C.Z. Dunn",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 261,
	title: "The Eagle's Talon",
	author: "John French",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"39m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 262,
	title: "Iron Corpses",
	author: "David Annandale",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"40m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/iron-corpses-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 263,
	title: "Garro: Ashes of Fealty",
	author: "James Swallow",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"18m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 264,
	title: "Raptor",
	author: "Gav Thorpe",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 265,
	title: "Grey Talon",
	author: "Chris Wraight",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"60m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 266,
	title: "Red-Marked",
	author: "Nick Kyme",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"75 Minutes",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 267,
	title: "Space Marine",
	author: "Graham McNeill",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"67m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 268,
	title: "The Heart of the Pharos",
	author: "L.J. Goulding",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"38m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 269,
	title: "The Thirteenth Wolf",
	author: "Gav Thorpe",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"68m",
	rating: "%",
	link:"http://www.blacklibrary.com/all-products/the-thirteenth-wolf-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 270,
	title: "Children of Sicarus",
	author: "Anthony Reynolds",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"39m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 271,
	title: "Perpetual",
	author: "Dan Abnett",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"27m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/perpetual-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 272,
	title: "",
	author: "Chris Wraight",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"25m",
	rating: "%",
	link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/the-soul-severed-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 273,
	title: "other uses",
	author: "Gav Thorpe",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 274,
	title: "The Binary Succession",
	author: "David Annandale",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"75m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 275,
	title: "Dark Compliance",
	author: "John French",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"64m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 276,
	title: "Blackshields: The False War",
	author: "Josh Reynolds",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"75m",
	rating: "%",
	link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/blackshields-the-false-war-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 277,
	title: "Blackshields: The Red Fief",
	author: "Josh Reynolds",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"1 hour 15m",
	rating: "%",
	link:"https://www.blacklibrary.com/the-horus-heresy/featured/blackshields-red-fief-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 278,
	title: "Hubris of Monarchia",
	author: "Andy Smillie",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/new-titles/featured/the-horus-heresy-hubris-of-monarchia-mp3.html"
},
{
	x: 1,
	y: 1,
	id: 279,
	title: "Nightfane",
	author: "Nick Kyme",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"1 hour 13m",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 280,
	title: "Blackshields: The Broken Chain",
	author: "Josh Reynolds",
	book:"Audio Dramas",
	faction: [""],
	pages:"",
	audio:"70m",
	rating: "%",
	link:"https://www.warhammer-community.com/2019/06/01/black-library-live-the-reveals/"
},
{
	x: 1,
	y: 1,
	id: 281,
	title: "2018 art and reference book",
	author: "",
	book: "",
	faction: [""],
	pages:"320",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 282,
	title: "2013 book",
	author: "",
	book: "",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 283,
	title: "Horus Heresy: The Scripts: Volume 1",
	author: "Dan Abnett",
	book: "",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 284,
	title: "Horus Heresy: The Scripts: Volume II",
	author: "John French",
	book: "",
	faction: [""],
	pages:"320",
	audio:"",
	rating: "%",
	link:""
},
{
	x: 1,
	y: 1,
	id: 285,
	title: "Macragge's Honour",
	author: "Dan Abnett",
	book: "",
	faction: [""],
	pages:"",
	audio:"",
	rating: "%",
	link:"https://www.blacklibrary.com/series/the-horus-heresy/horus-heresy-macragge's-honour-en-ebook-2019.html"
},
];