const horusHeresyDataBooks = [
    {
        x: 100,
        y: 200,
        id: 1,
        title: "Horus Rising",
        author: "Dan Abnett",
        book:"Book 1",
        faction: ["Sons of horus"],
        pages:"320 (hardcover) 416 (softcover)",
        audio:"12h 16m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/horus-rising.html"
    },
    {
        x: 400,
        y: 200,
        id: 2,
        title: "False Gods",
        author: "Graham McNeill",
        book:"Book 2",
        faction: ["Sons of horus"],
        pages:"416",
        audio:"11h 20m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/False-Gods-eBook.html"
    },
    {
        x: 700,
        y: 200,
        id: 3,
        title: "Galaxy in Flames",
        author: "Ben Counter",
        book:"Book 3",
        faction: ["Sons of horus"],
        pages:"416",
        audio:"8h 51m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/galaxy-in-flames-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 4,
        title: "The Flight of the Eisenstein",
        author: "James Swallow",
        book:"Book 4",
        faction: ["Sons of horus","Knight Errant"],
        pages:"416",
        audio:"12h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/flight-of-the-eisenstein-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 5,
        title: "Fulgrim",
        author: "Graham McNeill",
        book:"Book 5",
        faction: ["Emperor's Children"],
        pages:"512",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/fulgrim-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 6,
        title: "Descent of Angels",
        author: "Mitchel Scanlon",
        book:"Book 6",
        faction: ["Dark Angels"],
        pages:"416",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/descent-of-angels-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 7,
        title: "Legion",
        author: "Dan Abnett",
        book:"Book 7",
        faction: ["Alpha Legion","Perpetuals"],
        pages:"416",
        audio:"11h",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/legion-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 8,
        title: "Battle for the Abyss",
        author: "Ben Counter",
        book:"Book 8",
        faction: ["Word Bearers"],
        pages:"416",
        audio:"10h 42m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/battle-for-the-abyss-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 9,
        title: "Mechanicum",
        author: "Graham McNeill",
        book:"Book 9",
        faction: ["Mechanicum"],
        pages:"416",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/Mechanicum-eBook.html"
    },
    {
        x: 1,
        y: 1,
        id: 10,
        title: "Tales of Heresy",
        author: "Dan Abnett",
        book:"Book 10 Anthology",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/Tales-of-Heresy-eBook.html"
    },
    {
        x: 1,
        y: 1,
        id: 11,
        title: "Fallen Angels",
        author: "Mike Lee",
        book:"Book 11",
        faction: ["Dark Angels"],
        pages:"416",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/fallen-angels-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 12,
        title: "A Thousand Sons",
        author: "Graham McNeill",
        book:"Book 12",
        faction: ["Thousand Sons","Space Wolves"],
        pages:"416",
        audio:"16h",
        rating: "%",
        link:"http://www.blacklibrary.com/Blog/graham-mcneill-becomes-new-york-times-best-selling-author.html"
    },
    {
        x: 1,
        y: 1,
        id: 13,
        title: "Nemesis",
        author: "James Swallow",
        book:"Book 13",
        faction: ["Officio Assassinorum"],
        pages:"507",
        audio:"15h",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/Nemesis-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 14,
        title: "The First Heretic",
        author: "Aaron Dembski-Bowden",
        book:"Book 14",
        faction: ["Word Bearers"],
        pages:"502",
        audio:"14h 20m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/First-heretic-the-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 15,
        title: "Prospero Burns",
        author: "Dan Abnett",
        book:"Book 15",
        faction: ["Thousand Sons","Space Wolves"],
        pages:"416",
        audio:"15h",
        rating: "%",
        link:"http://www.blacklibrary.com/Blog/A-look-into-the-future.html"
    },
    {
        x: 1,
        y: 1,
        id: 16,
        title: "Age of Darkness",
        author: "Dan Abnett",
        book:"Book 16 Anthology",
        faction: [""],
        pages:"408",
        audio:"12h 30m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/age-of-darkness.html"
    },
    {
        x: 1,
        y: 1,
        id: 17,
        title: "The Outcast Dead",
        author: "Graham McNeill",
        book:"Book 17",
        faction: ["","Knight Errant"],
        pages:"416",
        audio:"14h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-outcast-dead-ebook-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 18,
        title: "Deliverance Lost",
        author: "Gav Thorpe",
        book:"Book 18",
        faction: ["Raven Gaurd"],
        pages:"480",
        audio:"16h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/deliverance-lost-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 19,
        title: "Know No Fear",
        author: "Dan Abnett",
        book:"Book 19",
        faction: ["Ultramarines","Word Bearers","Perpetuals"],
        pages:"416",
        audio:"11h",
        rating: "%",
        link:"http://www.blacklibrary.com/Blog/Questions-for-the-High-Lords_.html"
    },
    {
        x: 1,
        y: 1,
        id: 20,
        title: "The Primarchs",
        author: "Nick Kyme",
        book:"Book 20 Anthology",
        faction: [""],
        pages:"416",
        audio:"13h 30m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-primarchs-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 21,
        title: "Fear to Tread",
        author: "James Swallow",
        book:"Book 21",
        faction: ["Blood Angels"],
        pages:"516",
        audio:"15h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/fear-to-tread-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 22,
        title: "Shadows of Treachery",
        author: "Dan Abnett",
        book:"Book 22 Anthology",
        faction: [""],
        pages:"416",
        audio:"11h 44m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/shadows-of-treachery-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 23,
        title: "Angel Exterminatus",
        author: "Graham McNeill",
        book:"Book 23",
        faction: ["Iron Warriors","Emperor's Children","Iron Hands"],
        pages:"448",
        audio:"19h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/angel-exterminatus-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 24,
        title: "Betrayer",
        author: "Aaron Dembski-Bowden",
        book:"Book 24",
        faction: ["Ultramarines","World Eaters","Word Bearers","Perpetuals"],
        pages:"416",
        audio:"14h 9m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/betrayer-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 25,
        title: "Mark of Calth",
        author: "Dan Abnett",
        book:"Book 25 Anthology",
        faction: ["Ultramarines","Word Bearers","Perpetuals"],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/mark-of-calth-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 26,
        title: "Vulkan Lives",
        author: "Nick Kyme",
        book:"Book 26",
        faction: ["Salamanders","Night Lords","Perpetuals"],
        pages:"416",
        audio:"13h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/vulkan-lives-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 27,
        title: "The Unremembered Empire",
        author: "Dan Abnett",
        book:"Book 27",
        faction: ["Blood Angels","Ultramarines","Salamanders","Night Lords"],
        pages:"416",
        audio:"13h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-unremembered-empire-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 28,
        title: "Scars",
        author: "Chris Wraight",
        book:"Book 28",
        faction: ["Space Wolves","White Scars"],
        pages:"416",
        audio:"11h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/scars-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 29,
        title: "Vengeful Spirit ",
        author: "Graham McNeill",
        book:"Book 29",
        faction: ["Sons of Horus","Knight Errant"],
        pages:"544",
        audio:"15h",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 30,
        title: "The Damnation of Pythos",
        author: "David Annandale",
        book:"Book 30",
        faction: ["Iron Hands"],
        pages:"416",
        audio:"12h",
        rating: "%",
        link:"http://www.blacklibrary.com/Blog/new-hh-art.html"
    },
    {
        x: 1,
        y: 1,
        id: 31,
        title: "Legacies of Betrayal",
        author: "Aaron Dembski-Bowden",
        book:"Book 31 Anthology",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 32,
        title: "Deathfire",
        author: "Nick Kyme",
        book:"Book 32",
        faction: ["Salamanders"],
        pages:"416",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/deathfire-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 33,
        title: "War Without End",
        author: "Aaron Dembski-Bowden",
        book:"Book 33 Anthology",
        faction: [""],
        pages:"624",
        audio:"16h 11m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/hh-war-without-end-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 34,
        title: "Pharos",
        author: "Guy Haley",
        book:"Book 34",
        faction: ["Ultramarines","Night Lords"],
        pages:"480",
        audio:"13h 23m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/pharos-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 35,
        title: "Eye of Terra",
        author: "Aaron Dembski-Bowden Anthology",
        book:"Book 35",
        faction: [""],
        pages:"480",
        audio:"12h 18m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 36,
        title: "The Path of Heaven",
        author: "Chris Wraight",
        book:"Book 36",
        faction: ["White Scars","Emperor's Children","Death Guard"],
        pages:"432",
        audio:"13h 28m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/path-of-heaven-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 37,
        title: "The Silent War",
        author: "",
        book:"Book 37 Anthology",
        faction: [""],
        pages:"480",
        audio:"14h 2m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-silent-war-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 38,
        title: "Angels of Caliban",
        author: "Gav Thorpe",
        book:"Book 38",
        faction: ["Blood Angels","Night Lords","Dark Angels","Ultramarines"],
        pages:"480",
        audio:"10h 57m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/angels-of-caliban-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 39,
        title: "Praetorian of Dorn",
        author: "John French",
        book:"Book 39",
        faction: ["Alpha Legion","Imperial Fists"],
        pages:"478",
        audio:"12h 57m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-praetorian-of-dorn-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 40,
        title: "Corax",
        author: "Gav Thorpe",
        book:"Book 40 Anthology",
        faction: [""],
        pages:"464",
        audio:"12h 49m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/corax-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 41,
        title: "The Master of Mankind",
        author: "Aaron Dembski-Bowden",
        book:"Book 41",
        faction: ["Custodies & Sisters of Silence"],
        pages:"448",
        audio:"12h 34m",
        rating: "%",
        link:"https://aarondembskibowden.wordpress.com/2015/08/28/okay-okay-fine-this-is-what-im-writing/"
    },
    {
        x: 1,
        y: 1,
        id: 42,
        title: "Garro",
        author: "James Swallow",
        book:"Book 42 Anthology",
        faction: ["Knight Errant","Word Bearers"],
        pages:"384",
        audio:"12h 27m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-garro-weapon-of-fate-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 43,
        title: "Shattered Legions",
        author: "Dan Abnett",
        book:"Book 43 Anthology",
        faction: [""],
        pages:"496",
        audio:"13h 14m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 44,
        title: "The Crimson King",
        author: "Graham McNeill",
        book:"Book 44",
        faction: ["Thousand Sons","Knight Errant"],
        pages:"456",
        audio:"14h 46m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-the-crimson-king-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 45,
        title: "Tallarn",
        author: "John French",
        book:"Book 45 Anthology",
        faction: [""],
        pages:"480",
        audio:"12h 54m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 46,
        title: "Ruinstorm",
        author: "David Annandale",
        book:"Book 46",
        faction: ["Blood Angels","Dark Angels","Ultramarines"],
        pages:"480",
        audio:"10h 7m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 47,
        title: "Old Earth",
        author: "Nick Kyme",
        book:"Book 47",
        faction: ["Salamanders","Iron Hands","Perpetuals"],
        pages:"400",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/old-earth-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 48,
        title: "The Burden of Loyalty",
        author: "",
        book:"Book 48 Anthology",
        faction: [""],
        pages:"496",
        audio:"13h 44m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/the-burden-of-loyalty-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 49,
        title: "Wolfsbane",
        author: "Guy Haley",
        book:"Book 49",
        faction: ["Space Wolves","Sons of Horus"],
        pages:"400",
        audio:"11h 36m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/wolfsbane-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 50,
        title: "Born of Flame",
        author: "Nick Kyme",
        book:"Book 50 Anthology",
        faction: [""],
        pages:"544",
        audio:"15h 54m",
        rating: "%",
        link:"https://www.blacklibrary.com/prod-home/new-paperback/born-of-flame-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 51,
        title: "Slaves to Darkness",
        author: "John French",
        book:"Book 51",
        faction: ["Sons of Horus","Emperor's Children","Word Bearers","World Eaters"],
        pages:"432",
        audio:"10h 49m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 52,
        title: "Heralds of the Siege",
        author: "",
        book:"Book 52 Anthology",
        faction: [""],
        pages:"432",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 53,
        title: "Titandeath",
        author: "Guy Haley",
        book:"Book 53",
        faction: ["Mechanicum and Collegia Titanica"],
        pages:"480",
        audio:"13h and 40m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 54,
        title: "The Buried Dagger",
        author: "James Swallow",
        book:"Book 54",
        faction: ["Death Guard","Knight Errant"],
        pages:"400",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 55,
        title: "The Solar War",
        author: "John French",
        book:"Siege of Terra",
        faction: [""],
        pages:"384",
        audio:"12h 14m",
        rating: "%",
        link:"https://www.blacklibrary.com/coming-soon/may/siege-of-terra-the-solar-war-ebook-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 56,
        title: "The Lost and the Damned",
        author: "Guy Haley",
        book:"Siege of Terra",
        faction: [""],
        pages:"416",
        audio:"13h 2m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/the-lost-and-the-damned-ebook-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 57,
        title: "The First Wall",
        author: "Gav Thorpe",
        book:"Siege of Terra",
        faction: [""],
        pages:"460",
        audio:"12h 44m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/the-first-wall-ebook-2020.html"
    },
    {
        x: 1,
        y: 1,
        id: 58,
        title: "Sons of the Selenar",
        author: "Graham McNeill",
        book:"Siege of Terra",
        faction: ["Iron Hands"],
        pages:"192",
        audio:"4h 23m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/sons-of-the-selenar-mp3-2020.html"
    },
    {
        x: 1,
        y: 1,
        id: 59,
        title: "Saturnine",
        author: "Dan Abnett",
        book:"Siege of Terra",
        faction: [""],
        pages:"464",
        audio:"16h 48m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/saturine-mp3-2020.html"
    },
    {
        x: 1,
        y: 1,
        id: 60,
        title: "The Fury of Magnus",
        author: "Graham McNeill",
        book:"Siege of Terra",
        faction: ["Thousand Sons"],
        pages:"6h 44m",
        audio:"226",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/fury-of-magnus-mp3-2020.html"
    },
    {
        x: 1,
        y: 1,
        id: 61,
        title: "Mortis",
        author: "John French",
        book:"Siege of Terra",
        faction: [""],
        pages:"560",
        audio:"16h 26m",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/siege-of-terra-mortis-ebook-2021.html"
    },
    {
        x: 1,
        y: 1,
        id: 62,
        title: "Warhawk",
        author: "Chris Wraight",
        book:"Siege of Terra",
        faction: [""],
        pages:"482",
        audio:"14h 15m",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/warhawk-ebook-2021.html"
    },
    {
        x: 1,
        y: 1,
        id: 63,
        title: "Roboute Guilliman: Lord of Ultramar",
        author: "David Annandale",
        book:"The Primarchs",
        faction: ["Ultramarines"],
        pages:"240",
        audio:"4h 58m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/roboute-guilliman-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 64,
        title: "Leman Russ: The Great Wolf",
        author: "Chris Wraight",
        book:"The Primarchs",
        faction: ["Space Wolves"],
        pages:"240",
        audio:"6h 4m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/leman-russ-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 65,
        title: "Magnus the Red: Master of Prospero",
        author: "Graham McNeill",
        book:"The Primarchs",
        faction: ["Thousand Sons"],
        pages:"201",
        audio:"5h 45m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/magnus-the-red.html"
    },
    {
        x: 1,
        y: 1,
        id: 66,
        title: "Perturabo: The Hammer of Olympia",
        author: "Guy Haley",
        book:"The Primarchs",
        faction: ["Iron Warriors"],
        pages:"240",
        audio:"6h 49m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 67,
        title: "Lorgar: Bearer of the Word",
        author: "Gav Thorpe",
        book:"The Primarchs",
        faction: ["Word Bearers"],
        pages:"208",
        audio:"6h 37m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 68,
        title: "Fulgrim: The Palatine Phoenix",
        author: "Josh Reynolds",
        book:"The Primarchs",
        faction: ["Emperor's Children"],
        pages:"224",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/fulgrim-the-palatine-phoenix-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 69,
        title: "Ferrus Manus: Gorgon of Medusa",
        author: "David Guymer",
        book:"The Primarchs",
        faction: ["Iron Hands"],
        pages:"224",
        audio:"6h 15m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/ferrus-manus-gorgon-of-medusa-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 70,
        title: "Jaghatai Khan: Warhawk of Chogoris",
        author: "Chris Wraight",
        book:"The Primarchs",
        faction: ["White Scars"],
        pages:"224",
        audio:"6h 9m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 71,
        title: "Vulkan: Lord of Drakes",
        author: "David Annandale",
        book:"The Primarchs",
        faction: ["Salamanders"],
        pages:"224",
        audio:"4h 50m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 72,
        title: "Sons of the Emperor",
        author: "",
        book:"The Primarchs Anthology",
        faction: [""],
        pages:"254",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 73,
        title: "Corax: Lord of Shadows",
        author: "Guy Haley",
        book:"The Primarchs",
        faction: ["Raven Gaurd"],
        pages:"224",
        audio:"6h 32m",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/primarchs-corax-ebook-cs-2018.html"
    },
    {
        x: 1,
        y: 1,
        id: 74,
        title: "Angron: Slave of Nuceria",
        author: "Ian St. Martin",
        book:"The Primarchs",
        faction: ["World Eaters"],
        pages:"224",
        audio:"6h 1m",
        rating: "%",
        link:"https://www.blacklibrary.com/series/primarchs_/angron-slave-of-nuceria-ebook-mp3-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 75,
        title: "Scions of the Emperor",
        author: "",
        book:"The Primarchs Anthology",
        faction: [""],
        pages:"182",
        audio:"",
        rating: "%",
        link:"https://www.goodreads.com/book/show/43886241-scions-of-the-emperor?ac=1&from_search=true"
    },
    {
        x: 1,
        y: 1,
        id: 76,
        title: "Konrad Curze: The Night Haunter",
        author: "Guy Haley",
        book:"The Primarchs",
        faction: ["Night Lords"],
        pages:"280",
        audio:"6h 5m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/konrad-curze-the-night-haunter-mp3-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 77,
        title: "Lion El'Jonson: Lord of the First",
        author: "David Guymer",
        book:"The Primarchs",
        faction: ["Dark Angels"],
        pages:"320",
        audio:"5h 55m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/lion-eljonson-lord-of-the-first-ebook-2020.html"
    },
    {
        x: 1,
        y: 1,
        id: 78,
        title: "Alpharius: Head of the Hydra",
        author: "Mike Brooks",
        book:"The Primarchs",
        faction: ["Alpha Legion"],
        pages:"202",
        audio:"5h 23m",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/alpharius-head-of-the-hydra-mp3-2021.html"
    },
    {
        x: 1,
        y: 1,
        id: 79,
        title: "Blood of the Emperor",
        author: "",
        book:"The Primarchs",
        faction: [""],
        pages:"192",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 80,
        title: "Grandfather's Gift",
        author: "Guy Haley",
        book:"Short Stories",
        faction: ["Death Guard"],
        pages:"17",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/grandfathers-gift-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 82,
        title: "A Lesson in Iron",
        author: "David Guymer",
        book:"Short Stories",
        faction: [""],
        pages:"21",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/advent-2018-9-a-lesson-in-iron-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 83,
        title: "Ghost of Nuceria",
        author: "Ian St. Martin",
        book:"Short Stories",
        faction: [""],
        pages:"21",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/eater-of-cities-eng-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 84,
        title: "The Passing of Angels",
        author: "John French",
        book:"Short Stories",
        faction: [""],
        pages:"21",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 85,
        title: "The Abyssal Edge",
        author: "Aaron Dembski-Bowden",
        book:"Short Stories",
        faction: [""],
        pages:"30",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 86,
        title: "Mercy of the Dragon",
        author: "Nick Kyme",
        book:"Short Stories",
        faction: [""],
        pages:"41",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 87,
        title: "Will of the Legion",
        author: "Andy Clark",
        book:"Short Stories",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 88,
        title: "Embers of Extinction",
        author: "Brandon Easton",
        book:"Short Stories",
        faction: ["Iron Warriors"],
        pages:"",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 89,
        title: "Perturabo: Stone and Iron",
        author: "Robbie MacNiven",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"21m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 90,
        title: "Malcador: First Lord of the Imperium",
        author: "L.J. Goulding",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"25m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 91,
        title: "Konrad Curze: A Lesson in Darkness",
        author: "Ian St. Martin",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"27m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 92,
        title: "The Lords of Terra",
        author: "L.J. Goulding",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"1 hour 13m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 93,
        title: "Illyrium",
        author: "Darius Hinks",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"28m",
        rating: "%",
        link:"https://www.blacklibrary.com/prod-home/advent-home/illyrium-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 94,
        title: "The Revelation of the Word",
        author: "David Annandale",
        book:"Audio Dramas",
        faction: ["Word Bearers"],
        pages:"",
        audio:"24m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/the-revelation-of-the-word-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 95,
        title: "Morningstar",
        author: "Graham McNeill",
        book:"Audio Dramas",
        faction: ["Thousand Sons"],
        pages:"",
        audio:"24m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 96,
        title: "Valdor: Birth of the Imperium",
        author: "Chris Wraight",
        book:"Horus Heresy Characters Novels",
        faction: [""],
        pages:"272",
        audio:"6h 16m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 97,
        title: "Luther: First of the Fallen",
        author: "Gav Thorpe",
        book:"Horus Heresy Characters Novels",
        faction: ["Dark Angels","Death Guard"],
        pages:"224",
        audio:"7h 32m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 98,
        title: "Sigismund: The Eternal Crusader",
        author: "John French",
        book:"Horus Heresy Characters Novels",
        faction: [""],
        pages:"192",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 99,
        title: "Promethean Sun",
        author: "Nick Kyme",
        book:"Official Novellas",
        faction: ["Salamanders"],
        pages:"128",
        audio:"4h 5m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/promethean-sun-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 100,
        title: "Aurelian",
        author: "Aaron Dembski-Bowden",
        book:"Official Novellas",
        faction: ["Word Bearers"],
        pages:"128",
        audio:"3h 16m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/aurelian-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 101,
        title: "Brotherhood of the Storm",
        author: "Chris Wraight",
        book:"Official Novellas",
        faction: ["White Scars"],
        pages:"103",
        audio:"4h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/brotherhood-of-the-storm-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 102,
        title: "The Reflection Crack'd",
        author: "Graham McNeill",
        book:"Official Novellas",
        faction: ["Emperor's Children"],
        pages:"95",
        audio:"3h 38m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-reflection-crackd-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 103,
        title: "Feat of Iron",
        author: "Nick Kyme",
        book:"Official Novellas",
        faction: ["Iron Hands"],
        pages:"102",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/feat-of-iron-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 104,
        title: "The Lion",
        author: "Gav Thorpe",
        book:"Official Novellas",
        faction: ["Dark Angels","Death Guard"],
        pages:"95",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-lion-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 105,
        title: "The Serpent Beneath",
        author: "Rob Sanders",
        book:"Official Novellas",
        faction: ["Alpha Legion"],
        pages:"101",
        audio:"3h 43m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-serpent-beneath-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 106,
        title: "Corax: Soulforge",
        author: "Gav Thorpe",
        book:"Official Novellas",
        faction: ["Raven Gaurd"],
        pages:"128",
        audio:"3h 25m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/corax-soulforge-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 107,
        title: "Scorched Earth",
        author: "Nick Kyme",
        book:"Official Novellas",
        faction: ["Salamanders"],
        pages:"92",
        audio:"3h 50m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/scorched-earth-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 108,
        title: "Tallarn: Executioner",
        author: "John French",
        book:"Official Novellas",
        faction: ["Iron Warriors"],
        pages:"123",
        audio:"3h 58m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/tallarn-executioner-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 109,
        title: "Prince of Crows",
        author: "Aaron Dembski-Bowden",
        book:"Official Novellas",
        faction: ["Night Lords"],
        pages:"99",
        audio:"3h 20m",
        rating: "%",
        link:"https://web.archive.org/web/20170402224633/https://www.blacklibrary.com/the-horus-heresy/novels/prince-of-crows-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 110,
        title: "Crimson Fist",
        author: "John French",
        book:"Official Novellas",
        faction: [""],
        pages:"93",
        audio:"3h",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-crimson-fist-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 111,
        title: "The Purge",
        author: "Anthony Reynolds",
        book:"Official Novellas",
        faction: ["Ultramarines","Word Bearers"],
        pages:"114",
        audio:"3h 40m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-purge-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 112,
        title: "Ravenlord",
        author: "Gav Thorpe",
        book:"Official Novellas",
        faction: ["Raven Gaurd"],
        pages:"112",
        audio:"3h 40m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/ravenlord-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 113,
        title: "The Seventh Serpent",
        author: "Graham McNeill",
        book:"Official Novellas",
        faction: ["Iron Hands","Alpha Legion"],
        pages:"132",
        audio:"4h 27m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-seventh-serpent-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 114,
        title: "Tallarn: Ironclad",
        author: "John French",
        book:"Official Novellas",
        faction: ["Iron Warriors","Mechanicum","Word Bearers"],
        pages:"240",
        audio:"7h 26m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/tallarn-ironclad-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 115,
        title: "Cybernetica",
        author: "Rob Sanders",
        book:"Official Novellas",
        faction: ["Mechanicum","Knight Errant"],
        pages:"134",
        audio:"5h 11m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/cybernetica-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 116,
        title: "Wolf King",
        author: "Chris Wraight",
        book:"Official Novellas",
        faction: ["Space Wolves"],
        pages:"114",
        audio:"3h 54m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/wolf-king-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 117,
        title: "The Honoured",
        author: "Rob Sanders",
        book:"Official Novellas",
        faction: ["Ultramarines"],
        pages:"240",
        audio:"5h 37m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-honoured-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 118,
        title: "The Unburdened",
        author: "David Annandale",
        book:"Official Novellas",
        faction: ["Word Bearers"],
        pages:"192",
        audio:"5h 48m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/the-unburdened-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 120,
        title: "Sons of the Forge",
        author: "Nick Kyme",
        book:"Official Novellas",
        faction: ["Salamanders"],
        pages:"204",
        audio:"6h 38m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/sons-of-the-forge-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 121,
        title: "Dreadwing",
        author: "David Guymer",
        book:"Official Novellas",
        faction: ["Dark Angels"],
        pages:"114",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/series/novella-series-1/dreadwing-ebook-2018.html"
    },
    {
        x: 1,
        y: 1,
        id: 122,
        title: "Spear of Ultramar",
        author: "David Annandale",
        book:"Official Novellas",
        faction: ["Ultramarines"],
        pages:"100",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/spear-of-ultramar-ebook-2018.html"
    },
    {
        x: 1,
        y: 1,
        id: 123,
        title: "Angron",
        author: "Aaron Dembski-Bowden",
        book:"Collections Anthology",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/angron-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 124,
        title: "The Imperial Truth",
        author: "",
        book:"Collections Anthology",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-imperial-truth-ebook-collection.html"
    },
    {
        x: 1,
        y: 1,
        id: 125,
        title: "Sedition's Gate",
        author: "Nick Kyme",
        book:"Collections Anthology",
        faction: [""],
        pages:"142",
        audio:"",
        rating: "%",
        link:"http://www.blacklibrary.com/new-at-bl/Horus_Heresy_Weekender_and_New_Night_Lords_Art.html"
    },
    {
        x: 1,
        y: 1,
        id: 126,
        title: "Echoes of Ruin",
        author: "David Annandale",
        book:"Collections Anthology",
        faction: [""],
        pages:"",
        audio:"75m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/echoes-of-ruin.html"
    },
    {
        x: 1,
        y: 1,
        id: 127,
        title: "Death and Defiance",
        author: "Aaron Dembski-Bowden",
        book:"Collections Anthology",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/death-and-defiance-ebook-collection.html"
    },
    {
        x: 1,
        y: 1,
        id: 128,
        title: "Blades of the Traitor",
        author: "John French",
        book:"Collections Anthology",
        faction: [""],
        pages:"118",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 129,
        title: "Meduson",
        author: "Dan Abnett",
        book:"Collections Anthology",
        faction: ["Iron Hands"],
        pages:"279",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 130,
        title: "Betrayal at Calth",
        author: "David Annandale",
        book:"Collections Anthology",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 131,
        title: "Echoes of the Imperium",
        author: "",
        book:"Collections Anthology",
        faction: [""],
        pages:"",
        audio:"74m",
        rating: "%",
        link:"http://www.blacklibrary.com/all-products/echoes-of-imperium-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 133,
        title: "Echoes of Revelation",
        author: "Dan Abnett",
        book:"Collections Anthology",
        faction: [""],
        pages:"",
        audio:"75m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/hh-echoes-of-revelation-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 134,
        title: "The Lightning Tower",
        author: "Dan Abnett",
        book:"Short stories",
        faction: ["Imperial Fists"],
        pages:"20",
        audio:"40m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/lightning-tower-enhanced-audio.html"
    },
    {
        x: 1,
        y: 1,
        id: 135,
        title: "The Dark King",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Night Lords"],
        pages:"39",
        audio:"36m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/dark-king-enhanced-audio.html"
    },
    {
        x: 1,
        y: 1,
        id: 136,
        title: "Blood Games",
        author: "Dan Abnett",
        book:"Short stories",
        faction: ["Custodies & Sisters of Silence"],
        pages:"",
        audio:"1 hour 27m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/blood-games-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 137,
        title: "Wolf at the Door",
        author: "Mike Lee",
        book:"Short stories",
        faction: ["Space Wolves"],
        pages:"",
        audio:"2h 54m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/wolf-at-the-door-audio.html"
    },
    {
        x: 1,
        y: 1,
        id: 138,
        title: "Scions of the Storm",
        author: "Anthony Reynolds",
        book:"Short stories",
        faction: ["Word Bearers"],
        pages:"",
        audio:"1 hour 18m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/scions-of-the-storm-audio.html"
    },
    {
        x: 1,
        y: 1,
        id: 139,
        title: "The Voice",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Custodies"],
        pages:"",
        audio:"2h 2m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/the-voice-audio.html"
    },
    {
        x: 1,
        y: 1,
        id: 140,
        title: "Call of the Lion",
        author: "Gav Thorpe",
        book:"Short stories",
        faction: ["Dark Angels"],
        pages:"",
        audio:"1 hour 16m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/call-of-the-lion-audio.html"
    },
    {
        x: 1,
        y: 1,
        id: 141,
        title: "The Last Church",
        author: "Graham McNeill",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"1 hour 29m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/the-last-church-audio.html"
    },
    {
        x: 1,
        y: 1,
        id: 142,
        title: "After Desh'ea",
        author: "Matthew Farrer",
        book:"Short stories",
        faction: ["World Eaters"],
        pages:"",
        audio:"1 hour 7m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/after-deshea-audio.html"
    },
    {
        x: 1,
        y: 1,
        id: 143,
        title: "Rules of Engagement",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Ultramarines"],
        pages:"",
        audio:"1h 36m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/rules-of-engagement-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 144,
        title: "Liar's Due",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Alpha Legion"],
        pages:"",
        audio:"1h 33m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/liars-due-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 145,
        title: "Forgotten Sons",
        author: "Nick Kyme",
        book:"Short stories",
        faction: [""],
        pages:"1h 54m",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/forgotten-sons-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 146,
        title: "The Last Remembrancer",
        author: "John French",
        book:"Short stories",
        faction: ["Imperial Fists","Knight Errant"],
        pages:"",
        audio:"54m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/last-remembrancer-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 147,
        title: "Rebirth",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["Thousand Sons"],
        pages:"",
        audio:"1h 21m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/horus-heresy-rebirth-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 148,
        title: "The Face of Treachery",
        author: "Gav Thorpe",
        book:"Short stories",
        faction: ["Raven Gaurd"],
        pages:"",
        audio:"52m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/face-of-treachery-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 149,
        title: "Little Horus",
        author: "Dan Abnett",
        book:"Short stories",
        faction: ["Sons of Horus","Iron Hands"],
        pages:"",
        audio:"56m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/little-horus-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 150,
        title: "The Iron Within",
        author: "Rob Sanders",
        book:"Short stories",
        faction: ["Iron Warriors"],
        pages:"",
        audio:"1h 53m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/iron-within-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 151,
        title: "Savage Weapons",
        author: "Aaron Dembski-Bowden",
        book:"Short stories",
        faction: ["Dark Angels","Night Lords"],
        pages:"",
        audio:"1h 27m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/savage-weapons-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 152,
        title: "Army of One",
        author: "Rob Sanders",
        book:"Short stories",
        faction: ["Officio Assassinorum"],
        pages:"",
        audio:"8m",
        rating: "%",
        link:"http://www.blacklibrary.com/all-products/army-of-one-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 153,
        title: "Kryptos",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Iron Hands"],
        pages:"",
        audio:"40m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 154,
        title: "Distant Echoes of Old Night",
        author: "Rob Sanders",
        book:"Short stories",
        faction: ["Death Guard"],
        pages:"",
        audio:"53m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 155,
        title: "Lost Sons",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Knight Errant"],
        pages:"",
        audio:"42m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/lost_sons.html"
    },
    {
        x: 1,
        y: 1,
        id: 156,
        title: "Death of a Silversmith",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Sons of Horus"],
        pages:"",
        audio:"30m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/death_of_a_silversmith.html"
    },
    {
        x: 1,
        y: 1,
        id: 157,
        title: "The Divine Word",
        author: "Gav Thorpe",
        book:"Short stories",
        faction: ["Raven Gaurd"],
        pages:"",
        audio:"43m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 158,
        title: "The Kaban Project",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Mechanicum"],
        pages:"",
        audio:"1h 39m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 159,
        title: "The Gates of Terra",
        author: "Nick Kyme",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"40m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/gates-of-terra-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 160,
        title: "Lord of the Red Sands",
        author: "Aaron Dembski-Bowden",
        book:"Short stories",
        faction: ["World Eaters"],
        pages:"",
        audio:"11m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/lord-of-the-red-sands-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 161,
        title: "Serpent",
        author: "John French",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"12m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/serpent-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 162,
        title: "Luna Mendax",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Knight Errant"],
        pages:"",
        audio:"38m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/luna-mendax-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 163,
        title: "Riven",
        author: "John French",
        book:"Short stories",
        faction: ["Iron Hands"],
        pages:"",
        audio:"1 hour 25m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/riven-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 164,
        title: "Lone Wolf",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["Space Wolves"],
        pages:"",
        audio:"11m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/advent-day-one-bjorn-lone-wolf-eBook.html"
    },
    {
        x: 1,
        y: 1,
        id: 165,
        title: "The Wolf of Ash and Fire",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Sons of Horus"],
        pages:"",
        audio:"1h 17m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 166,
        title: "Heart of the Conqueror",
        author: "Aaron Dembski-Bowden",
        book:"Short stories",
        faction: ["World Eaters"],
        pages:"",
        audio:"12m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/heart-of-the-conquerer-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 167,
        title: "Child of Night",
        author: "John French",
        book:"Short stories",
        faction: ["Knight Errant","Night Lords"],
        pages:"",
        audio:"38m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/child-of-night-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 168,
        title: "The Devine Adoratrice",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Sons of Horus"],
        pages:"",
        audio:"1h 54m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-devine-adoratrice-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 169,
        title: "Daemonology",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["Death Guard"],
        pages:"",
        audio:"46m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/daemonology-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 170,
        title: "Sins of the Father",
        author: "Andy Smillie",
        book:"Short stories",
        faction: ["Blood Angels"],
        pages:"",
        audio:"13m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/sins-of-the-father-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 171,
        title: "The Final Compliance of Sixty-Three Fourteen",
        author: "Guy Haley",
        book:"Short stories",
        faction: ["Sons of Horus"],
        pages:"",
        audio:"18m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/final-compliance-of-63-14-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 172,
        title: "Vorax",
        author: "Matthew Farrer",
        book:"Short stories",
        faction: ["Mechanicum"],
        pages:"",
        audio:"15m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/vorax-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 173,
        title: "The Value of Fear",
        author: "Gav Thorpe",
        book:"Short stories",
        faction: ["Raven Gaurd","Night Lords"],
        pages:"",
        audio:"15m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/value-of-fear-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 174,
        title: "Brotherhood of the Moon",
        author: "Chris Wraight",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"18m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/brotherhood-of-the-moon-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 175,
        title: "Virtues of the Sons",
        author: "Andy Smillie",
        book:"Short stories",
        faction: ["Blood Angels"],
        pages:"",
        audio:"37m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/virtues-sons-sins-father-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 176,
        title: "Imperfect",
        author: "Nick Kyme",
        book:"Short stories",
        faction: ["Emperor's Children"],
        pages:"",
        audio:"34m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/imperfect-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 177,
        title: "Howl of the Hearthworld",
        author: "Aaron Dembski-Bowden",
        book:"Short stories",
        faction: ["Space Wolves"],
        pages:"",
        audio:"29m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/howl-of-the-hearthworld-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 178,
        title: "A Safe and Shadowed Place",
        author: "Guy Haley",
        book:"Short stories",
        faction: ["Ultramarines","Night Lords"],
        pages:"",
        audio:"46m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/safe-and-shadowed-place-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 179,
        title: "Gunsight",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Word Bearers"],
        pages:"",
        audio:"1h 20m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/gunsight-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 180,
        title: "Black Oculus",
        author: "John French",
        book:"Short stories",
        faction: ["Emperor's Children","Iron Hands"],
        pages:"",
        audio:"10m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/black-oculus-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 181,
        title: "Wolf Mother",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Knight Errant","Perpetuals"],
        pages:"",
        audio:"1 hour 12m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/wolf-mother-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 182,
        title: "Twisted",
        author: "Guy Haley",
        book:"Short stories",
        faction: ["Sons of Horus"],
        pages:"",
        audio:"1 hour 18m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/twisted-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 183,
        title: "Chirurgeon",
        author: "Nick Kyme",
        book:"Short stories",
        faction: ["Emperor's Children"],
        pages:"",
        audio:"45m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/chirugeon-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 184,
        title: "Tallarn: Witness",
        author: "John French",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"7m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/tallarn-witness-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 185,
        title: "Ironfire",
        author: "Rob Sanders",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"57m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/ironfire-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 186,
        title: "Hands of the Emperor",
        author: "Rob Sanders",
        book:"Short stories",
        faction: ["Custodies"],
        pages:"",
        audio:"1h 9m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/hands-of-the-emperor-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 187,
        title: "By the Lion's Command",
        author: "Gav Thorpe",
        book:"Short stories",
        faction: ["Dark Angels","Death Guard"],
        pages:"",
        audio:"35m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/by-the-lions-command-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 188,
        title: "All That Remains",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Knight Errant"],
        pages:"",
        audio:"39m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/all-that-remains-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 189,
        title: "The Phoenician",
        author: "Nick Kyme",
        book:"Short stories",
        faction: ["Emperor's Children"],
        pages:"",
        audio:"13m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-phoenician-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 190,
        title: "Artefacts",
        author: "Nick Kyme",
        book:"Short stories",
        faction: ["Salamanders"],
        pages:"",
        audio:"32m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/artefacts-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 191,
        title: "Ghosts Speak Not",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Custodies & Sisters of Silence","Knight Errant"],
        pages:"",
        audio:"2h 1m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/ghosts-speak-not-patience-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 192,
        title: "Patience",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Knight Errant"],
        pages:"",
        audio:"14m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/ghosts-speak-not-patience-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 193,
        title: "Tallarn: Siren",
        author: "John French",
        book:"Short stories",
        faction: ["Iron Warriors"],
        pages:"",
        audio:"1h 27m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/tallarn-siren-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 194,
        title: "Inheritor",
        author: "Gav Thorpe",
        book:"Short stories",
        faction: ["World Eaters","Word Bearers"],
        pages:"",
        audio:"39m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/hh-inheritor-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 195,
        title: "Blackshield",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["Death Guard"],
        pages:"",
        audio:"47m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/blackshield.html"
    },
    {
        x: 1,
        y: 1,
        id: 196,
        title: "Myriad",
        author: "Rob Sanders",
        book:"Short stories",
        faction: ["Mechanicum"],
        pages:"",
        audio:"59m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/myriad.html"
    },
    {
        x: 1,
        y: 1,
        id: 197,
        title: "Into Exile",
        author: "Aaron Dembski-Bowden",
        book:"Short stories",
        faction: ["Mechanicum"],
        pages:"",
        audio:"35m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/into-exile-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 198,
        title: "The Grey Raven",
        author: "Gav Thorpe",
        book:"Short stories",
        faction: ["Raven Gaurd","Knight Errant"],
        pages:"",
        audio:"38m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-grey-raven-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 199,
        title: "The Painted Count",
        author: "Guy Haley",
        book:"Short stories",
        faction: ["Night Lords"],
        pages:"",
        audio:"43m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/the-painted-count-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 200,
        title: "Exocytosis",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Death Guard"],
        pages:"",
        audio:"58m",
        rating: "%",
        link:"http://www.blacklibrary.com/all-products/exocytosis-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 201,
        title: "The Last Son of Prospero",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["Thousand Sons","White Scars"],
        pages:"",
        audio:"46m",
        rating: "%",
        link:"http://www.blacklibrary.com/all-products/the-last-son-of-prospero-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 202,
        title: "Ordo Sinister",
        author: "John French",
        book:"Short stories",
        faction: ["Custodies & Sisters of Silence","Mechanicum and Collegia Titanica"],
        pages:"",
        audio:"43m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/hh-at-ordo-sinister-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 203,
        title: "The Ember Wolves",
        author: "Rob Sanders",
        book:"Short stories",
        faction: ["Mechanicum"],
        pages:"",
        audio:"39m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/hh-at-the-ember-wolves-eboo.html"
    },
    {
        x: 1,
        y: 1,
        id: 204,
        title: "Restorer",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["White Scars"],
        pages:"18",
        audio:"",
        rating: "%",
        link:"http://www.blacklibrary.com/all-products/restorer-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 205,
        title: "The Laurel of Defiance",
        author: "Guy Haley",
        book:"Short stories",
        faction: ["Ultramarines"],
        pages:"",
        audio:"57m",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/the-laurel-of-defiance-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 206,
        title: "Immortal Duty",
        author: "Nick Kyme",
        book:"Short stories",
        faction: ["Iron Hands"],
        pages:"",
        audio:"45m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/immortal-duty-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 207,
        title: "A Lesson in Iron",
        author: "David Guymer",
        book:"Short stories",
        faction: [""],
        pages:"22",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/advent-2018-9-a-lesson-in-iron-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 208,
        title: "The Atonement of Fire",
        author: "David Annandale",
        book:"Short stories",
        faction: ["Ultramarines"],
        pages:"23",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/prod-home/advent-2018/adventa2018-16-atonement-of-fire-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 209,
        title: "Duty Waits",
        author: "Guy Haley",
        book:"Short stories",
        faction: ["Imperial Fists"],
        pages:"",
        audio:"43m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/duty-waits-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 210,
        title: "Magisterium",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["Custodies & Sisters of Silence"],
        pages:"",
        audio:"44",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/magisterium-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 211,
        title: "Now Peals Midnight",
        author: "John French",
        book:"Short stories",
        faction: ["Imperial Fists"],
        pages:"",
        audio:"33m",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/now-peals-midnight-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 212,
        title: "Dreams of Unity",
        author: "Nick Kyme",
        book:"Short stories",
        faction: ["Custodies & Sisters of Silence"],
        pages:"",
        audio:"1h 1m",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/dreams-of-unity-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 213,
        title: "The Board is Set",
        author: "Gav Thorpe",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"37m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-board-is-set-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 214,
        title: "Champion of Oaths",
        author: "John French",
        book:"Short stories",
        faction: ["Imperial Fists"],
        pages:"17",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/eshort-champion-of-oaths.html"
    },
    {
        x: 1,
        y: 1,
        id: 215,
        title: "Child of Chaos",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["Word Bearers"],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/child-of-chaos-eshort-2020.html"
    },
    {
        x: 1,
        y: 1,
        id: 216,
        title: "Massacre",
        author: "Aaron Dembski-Bowden",
        book:"Short stories",
        faction: ["Night Lords"],
        pages:"",
        audio:"38m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/massacre-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 217,
        title: "Two Metaphysical Blades",
        author: "Chris Wraight",
        book:"Short stories",
        faction: ["Custodies"],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/eshort-two-metaphysical-blades.html"
    },
    {
        x: 1,
        y: 1,
        id: 218,
        title: "Prologue to Nikaea",
        author: "David Annandale",
        book:"Short stories",
        faction: [""],
        pages:"22",
        audio:"38m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/eshort-prologue-to-nikaea.html"
    },
    {
        x: 1,
        y: 1,
        id: 219,
        title: "Old Wounds, New Scars",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Perpetuals"],
        pages:"27",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/advent-2018-1-old-wounds-new-scars-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 220,
        title: "Abyssal",
        author: "David Annandale",
        book:"Short stories",
        faction: ["Custodies"],
        pages:"20",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/advent-2018-6-abyssal-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 221,
        title: "The Last Council",
        author: "L.J. Goulding",
        book:"Short stories",
        faction: ["Perpetuals"],
        pages:"",
        audio:"57m",
        rating: "%",
        link:"https://www.blacklibrary.com/prod-home/new/advent-2018-12-the-last-council-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 222,
        title: "A Rose Watered with Blood",
        author: "Aaron Dembski-Bowden",
        book:"Short stories",
        faction: ["World Eaters"],
        pages:"24",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/advent-2018-24-rose-watered-blood-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 223,
        title: "Bringer of Sorrow",
        author: "Aaron Dembski-Bowden",
        book:"Short stories",
        faction: ["Mechanicum and Collegia Titanica"],
        pages:"20",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/bringer-of-sorrows-eng-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 224,
        title: "Lantern's Light",
        author: "James Swallow",
        book:"Short stories",
        faction: ["Death Guard"],
        pages:"25",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/prod-home/library/lanterns-light-eng-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 225,
        title: "The Serpent's Dance",
        author: "Mike Brooks",
        book:"Short stories",
        faction: ["Custodies & Sisters of Silence"],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/prod-home/12-tales-of-christmas/the-serpents-dance-eshort-2020.html"
    },
    {
        x: 1,
        y: 1,
        id: 226,
        title: "The Lightning Hall",
        author: "Graham McNeill",
        book:"Short stories",
        faction: ["Mechanicum"],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/prod-home/12-tales-of-christmas/the-lighting-hall-eshort-2020.html"
    },
    {
        x: 1,
        y: 1,
        id: 227,
        title: "Eater of Dreams",
        author: "Marc Collins",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/eshort-eater-of-dreams-eng-2021.html"
    },
    {
        x: 1,
        y: 1,
        id: 228,
        title: "Bloodhowl",
        author: "Chris Forrester",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/eshort-bloodhowl-eng-2021.html"
    },
    {
        x: 1,
        y: 1,
        id: 229,
        title: "Amor Fati",
        author: "Michael F. Haspil",
        book:"Short stories",
        faction: [""],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/eshort-amor-fati-eng-2021.html"
    },
    {
        x: 1,
        y: 1,
        id: 234,
        title: "Raven's Flight",
        author: "Gav Thorpe",
        book:"Audio Dramas",
        faction: ["Raven Gaurd"],
        pages:"",
        audio:"75m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/Ravens-Flight-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 237,
        title: "Butcher's Nails",
        author: "Aaron Dembski-Bowden",
        book:"Audio Dramas",
        faction: ["World Eaters"],
        pages:"",
        audio:"1 hour 13m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/butchers-nails-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 238,
        title: "Grey Angel",
        author: "John French",
        book:"Audio Dramas",
        faction: ["Knight Errant"],
        pages:"",
        audio:"35m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/grey-angel-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 239,
        title: "Burden of Duty",
        author: "James Swallow",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"5m",
        rating: "%",
        link:"https://www.blacklibrary.com/series/garro/burden-of-duty-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 241,
        title: "Warmaster",
        author: "John French",
        book:"Audio Dramas",
        faction: ["Sons of Horus"],
        pages:"",
        audio:"9m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/warmaster-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 242,
        title: "Strike and Fade",
        author: "Guy Haley",
        book:"Audio Dramas",
        faction: ["Salamanders"],
        pages:"",
        audio:"10m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/strike-and-fade-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 243,
        title: "Veritas Ferrum",
        author: "David Annandale",
        book:"Audio Dramas",
        faction: ["Iron Hands"],
        pages:"",
        audio:"11m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/veritas-ferrum-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 244,
        title: "The Sigillite",
        author: "Chris Wraight",
        book:"Audio Dramas",
        faction: ["Perpetuals"],
        pages:"",
        audio:"1h 15m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-sigillite-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 245,
        title: "Honour to the Dead",
        author: "Gav Thorpe",
        book:"Audio Dramas",
        faction: ["Mechanicum"],
        pages:"",
        audio:"1h 15m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/Honour-to-the-Dead.html"
    },
    {
        x: 1,
        y: 1,
        id: 246,
        title: "Wolf Hunt",
        author: "Graham McNeill",
        book:"Audio Dramas",
        faction: ["Knight Errant"],
        pages:"",
        audio:"1h 20m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/wolf-hunt-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 247,
        title: "Censure",
        author: "Nick Kyme",
        book:"Audio Dramas",
        faction: ["Ultramarines","Word Bearers"],
        pages:"",
        audio:"1h 15m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/censure-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 248,
        title: "Thief of Revelations",
        author: "Graham McNeill",
        book:"Audio Dramas",
        faction: ["Thousand Sons"],
        pages:"",
        audio:"35m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/thief-of-revelations-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 249,
        title: "Khârn: The Eightfold Path",
        author: "Anthony Reynolds",
        book:"Audio Dramas",
        faction: ["World Eaters"],
        pages:"",
        audio:"12m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/advent-day-eight-kharn-the-eightfold-path-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 250,
        title: "Lucius: The Eternal Blademaster",
        author: "Graham McNeill",
        book:"Audio Dramas",
        faction: ["Emperor's Children"],
        pages:"",
        audio:"12m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/advent-day-twenty-one-lucius-the-eternal-blade.html"
    },
    {
        x: 1,
        y: 1,
        id: 251,
        title: "Cypher: Guardian of Order",
        author: "Gav Thorpe",
        book:"Audio Dramas",
        faction: ["Dark Angels"],
        pages:"",
        audio:"12m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/advent-day-twenty-five-cypher-guardian-of-order.html"
    },
    {
        x: 1,
        y: 1,
        id: 252,
        title: "Hunter's Moon",
        author: "Guy Haley",
        book:"Audio Dramas",
        faction: ["Space Wolves","Alpha Legion"],
        pages:"",
        audio:"35m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/hunters-moon-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 253,
        title: "Wolf's Claw",
        author: "Chris Wraight",
        book:"Audio Dramas",
        faction: ["Space Wolves"],
        pages:"",
        audio:"10m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/wolfs-claw-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 254,
        title: "Templar",
        author: "John French",
        book:"Audio Dramas",
        faction: ["Imperial Fists"],
        pages:"",
        audio:"65m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/templar-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 256,
        title: "Master of the First",
        author: "Gav Thorpe",
        book:"Audio Dramas",
        faction: ["Dark Angels"],
        pages:"",
        audio:"36m",
        rating: "%",
        link:"https://www.blacklibrary.com/all-products/master-of-the-first-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 257,
        title: "The Long Night",
        author: "Aaron Dembski-Bowden",
        book:"Audio Dramas",
        faction: ["Dark Angels","Night Lords"],
        pages:"",
        audio:"42m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-long-night-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 258,
        title: "Stratagem",
        author: "Nick Kyme",
        book:"Audio Dramas",
        faction: ["Ultramarines"],
        pages:"",
        audio:"21m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/stratagem-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 259,
        title: "Herald of Sanguinius",
        author: "Andy Smillie",
        book:"Audio Dramas",
        faction: ["Blood Angels"],
        pages:"",
        audio:"20m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/herald-of-sanguinius-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 260,
        title: "The Watcher",
        author: "C.Z. Dunn",
        book:"Audio Dramas",
        faction: ["Knight Errant"],
        pages:"",
        audio:"20m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-watcher-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 261,
        title: "The Eagle's Talon",
        author: "John French",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"39m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-eagles-talon-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 262,
        title: "Iron Corpses",
        author: "David Annandale",
        book:"Audio Dramas",
        faction: ["Iron Warriors"],
        pages:"",
        audio:"40m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/iron-corpses-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 264,
        title: "Raptor",
        author: "Gav Thorpe",
        book:"Audio Dramas",
        faction: ["Raven Gaurd"],
        pages:"",
        audio:"69m",
        rating: "%",
        link:"https://www.blacklibrary.com/authors/gav-thorpe/raptor-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 265,
        title: "Grey Talon",
        author: "Chris Wraight",
        book:"Audio Dramas",
        faction: ["Iron Hands","White Scars"],
        pages:"",
        audio:"1h",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/hh-grey-talon-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 266,
        title: "Red-Marked",
        author: "Nick Kyme",
        book:"Audio Dramas",
        faction: ["Ultramarines"],
        pages:"",
        audio:"1h 15m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/hh-red-marked-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 267,
        title: "The Either",
        author: "Graham McNeill",
        book:"Audio Dramas",
        faction: ["Iron Hands","Sons of Horus"],
        pages:"",
        audio:"67m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/hh-the-either-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 268,
        title: "The Heart of the Pharos",
        author: "L.J. Goulding",
        book:"Audio Dramas",
        faction: ["Ultramarines"],
        pages:"",
        audio:"38m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/heart-of-the-pharos-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 269,
        title: "The Thirteenth Wolf",
        author: "Gav Thorpe",
        book:"Audio Dramas",
        faction: ["Space Wolves"],
        pages:"",
        audio:"68m",
        rating: "%",
        link:"http://www.blacklibrary.com/all-products/the-thirteenth-wolf-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 270,
        title: "Children of Sicarus",
        author: "Anthony Reynolds",
        book:"Audio Dramas",
        faction: ["Word Bearers"],
        pages:"",
        audio:"39m",
        rating: "%",
        link:""
    },
    {
        x: 1,
        y: 1,
        id: 271,
        title: "Perpetual",
        author: "Dan Abnett",
        book:"Audio Dramas",
        faction: ["Perpetuals"],
        pages:"",
        audio:"27m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/perpetual-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 272,
        title: "The Soul, Severed",
        author: "Chris Wraight",
        book:"Audio Dramas",
        faction: ["Emperor's Children"],
        pages:"",
        audio:"25m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audio-dramas/the-soul-severed-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 273,
        title: "Valerius",
        author: "Gav Thorpe",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"22m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/valerius.mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 274,
        title: "The Binary Succession",
        author: "David Annandale",
        book:"Audio Dramas",
        faction: ["Mechanicum and Collegia Titanica"],
        pages:"",
        audio:"1h 15m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/binary-succession.html"
    },
    {
        x: 1,
        y: 1,
        id: 275,
        title: "Dark Compliance",
        author: "John French",
        book:"Audio Dramas",
        faction: [""],
        pages:"",
        audio:"1h 4m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/dark-compliance.html"
    },
    {
        x: 1,
        y: 1,
        id: 276,
        title: "Blackshields: The False War",
        author: "Josh Reynolds",
        book:"Audio Dramas",
        faction: ["Death Guard"],
        pages:"",
        audio:"75m",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/the-horus-heresy/blackshields-the-false-war-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 277,
        title: "Blackshields: The Red Fief",
        author: "Josh Reynolds",
        book:"Audio Dramas",
        faction: ["Death Guard"],
        pages:"",
        audio:"1 hour 15m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/featured/blackshields-red-fief-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 278,
        title: "Hubris of Monarchia",
        author: "Andy Smillie",
        book:"Audio Dramas",
        faction: ["Ultramarines"],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/new-titles/featured/the-horus-heresy-hubris-of-monarchia-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 279,
        title: "Nightfane",
        author: "Nick Kyme",
        book:"Audio Dramas",
        faction: ["Ultramarines"],
        pages:"",
        audio:"1h 13m",
        rating: "%",
        link:"https://www.blacklibrary.com/series/the-horus-heresy/the-horus-heresy-nightfane-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 280,
        title: "Blackshields: The Broken Chain",
        author: "Josh Reynolds",
        book:"Audio Dramas",
        faction: ["Death Guard"],
        pages:"",
        audio:"1h 10m",
        rating: "%",
        link:"https://www.warhammer-community.com/2019/06/01/black-library-live-the-reveals/"
    },
    {
        x: 1,
        y: 1,
        id: 285,
        title: "Macragge's Honour",
        author: "Dan Abnett",
        book: "Graphic Novel",
        faction: ["Ultramarines","Word Bearers"],
        pages:"128",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/series/the-horus-heresy/horus-heresy-macragge's-honour-en-ebook-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 285,
        title: "Allegiance",
        author: "Chris Wraight",
        book: "Short Story",
        faction: ["White Scars"],
        pages:"",
        audio:"1h 5m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/hh-allegiance-thousand-sons-and-white-scars-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 286,
        title: "The Keys of Hel",
        author: "John French",
        book: "Short Story",
        faction: ["Iron Hands"],
        pages:"",
        audio:"39m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-shattered-legions-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 287,
        title: "The Harrowing",
        author: "Rob Sanders",
        book: "Short Story",
        faction: ["Alpha Legion"],
        pages:"",
        audio:"55m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/quick-reads/the-harrowing-eshort.html"
    },
    {
        x: 1,
        y: 1,
        id: 288,
        title: "The Noose",
        author: "David Annandale",
        book: "Short Story",
        faction: ["Emperor's Children","Iron Hands"],
        pages:"",
        audio:"1h 4m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/meduson-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 289,
        title: "Serpent",
        author: "John French",
        book: "Short Story",
        faction: [""],
        pages:"",
        audio:"12m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/serpent-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 290,
        title: "The Shadowmasters",
        author: "Gav Thorpe",
        book: "Short Story",
        faction: ["Raven Gaurd"],
        pages:"",
        audio:"10m",
        rating: "%",
        link:"https://www.blacklibrary.com/audio/the-horus-heresy-audiobooks/the-shadowmasters-mp3.html"
    },
    {
        x: 1,
        y: 1,
        id: 291,
        title: "Weregeld",
        author: "Gav Thorpe",
        book: "Novella",
        faction: ["Raven Gaurd"],
        pages:"",
        audio:"4h 5m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/corax-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 292,
        title: "Deeds Endure",
        author: "Gav Thorpe",
        book: "Short Story",
        faction: [""],
        pages:"",
        audio:"56m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-shattered-legions-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 293,
        title: "Unforged",
        author: "Guy Haley",
        book: "Short Story",
        faction: ["Salamanders"],
        pages:"",
        audio:"17m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-shattered-legions-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 294,
        title: "The Hand Elect",
        author: "Chris Wraight",
        book: "Short Story",
        faction: ["Iron Hands"],
        pages:"",
        audio:"42m",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/hh-shattered-legions-ebook.html"
    },
    {
        x: 1,
        y: 1,
        id: 295,
        title: "Terminus",
        author: "Chris Wraight",
        book: "Short Story",
        faction: ["Death Guard"],
        pages:"",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/featured/blood-of-the-emperor-ebook-2021.html"
    },
    {
        x: 1,
        y: 1,
        id: 296,
        title: "Misbegotten",
        author: "Dan Abnett",
        book: "Short Story",
        faction: [""],
        pages:"17",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/sons-of-the-emperor-eng-2019.html"
    },
    {
        x: 1,
        y: 1,
        id: 297,
        title: "Prince of Blood",
        author: "Laurie Goulding",
        book: "Short Story",
        faction: ["World Eaters"],
        pages:"22",
        audio:"",
        rating: "%",
        link:"https://www.blacklibrary.com/the-horus-heresy/novels/sons-of-the-emperor-eng-2019.html"
    },
];
export default horusHeresyDataBooks;
/*
    {
        x:1,
        y:1,
        id: 70,
        title: "",
        author: "",
        book:"Characters Novels",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
*/


export const horusHeresyDataArrow = [
    {
        id:1,
        color:"red",
        type:"primary",
        dimension:[{x:340,y:150,length:100,height:20},{x:340,y:150,length:20,height:100}]
    },
    {   
        id:2,
        color:"blue",
        type:"secondary",
        dimension:[{x:200,y:100,length:100,height:20}]
    },
    {
        id:3,
        color:"green",
        type:"tertiary",
        dimension:[{x:300,y:100,length:100,height:20}]
    },
];