const horusHeresyDataBooks = [
    {
        x:100,
        y:200,
        id: 1,
        title: "Horus Rising",
        author: "Dan Abnett",
        book:"Book 1",
        faction:["Sons of horus"],
        pages:"320 (hardcover) 416 (softcover)",
        audio:"12h 16m",
        rating:"95%",
        link: "https://www.blacklibrary.com/the-horus-heresy/novels/horus-rising.html",
    },
    {
        x:400,
        y:200,
        id: 2,
        title: "False Gods",
        author: "Graham McNeill",
        book:"Book 2",
        faction:["Sons of horus"],
        pages:"416",
        audio:"11h 20m",
        rating:"75%",
        link: "https://www.blacklibrary.com/the-horus-heresy/novels/False-Gods-eBook.html",
    },
    {
        x:700,
        y:200,
        id: 3,
        title: "Galaxy in Flames",
        author: "Dan Abnett",
        book:"Book 3",
        faction:["Sons of horus"],
        pages:"416",
        audio:"8h 51m",
        rating:"75%",
        link: "https://www.blacklibrary.com/the-horus-heresy/novels/galaxy-in-flames-ebook.html",
    },
    {
        x:300,
        y:500,
        id: 4,
        title: "The Flight of the Eisenstein",
        author: "James Swallow",
        book:"Book 4",
        faction:["Sons of horus","Knight Errant"],
        pages:"416",
        audio:"12h",
        rating:"75%",
        link: "https://www.blacklibrary.com/the-horus-heresy/novels/flight-of-the-eisenstein-ebook.html",
    },
    {
        x:1,
        y:1,
        id: 5,
        title: "Fulgrim",
        author: "Graham McNeill",
        book:"Book 5",
        faction:["Emperor's Children"],
        pages:"512",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 6,
        title: "Descent of Angels",
        author: "Mitchel Scanlon",
        book:"Book 6",
        faction:["Dark Angels"],
        pages:"416",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 7,
        title: "Legion",
        author: "Dan Abnett",
        book:"Book 7",
        faction:["Alpha Legion","Perpetuals"],
        pages:"412",
        audio:"11h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 8,
        title: "Battle for the Abyss",
        author: "Ben Counter",
        book:"Book 8",
        faction:[""],
        pages:"416",
        audio:"10h 42m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 9,
        title: "Mechanicum",
        author: "Graham McNeill",
        book:"Book 9",
        faction:["Mechanicum"],
        pages:"416",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 11,
        title: "Fallen Angels",
        author: "Mike Lee",
        book:"Book 11",
        faction:[""],
        pages:"416",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 12,
        title: "A Thousand Sons",
        author: "Graham McNeill",
        book:"Book 12",
        faction:["Thousand Sons"],
        pages:"416",
        audio:"16h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 13,
        title: "Nemesis",
        author: "James Swallow",
        book:"Book 13",
        faction:["Officio Assassinorum"],
        pages:"507",
        audio:"15h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 14,
        title: "The First Heretic",
        author: "Aaron Dembski-Bowden",
        book:"Book 14",
        faction:[""],
        pages:"502",
        audio:"14h 20m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 15,
        title: "Prospero Burns",
        author: "Dan Abnett",
        book:"Book 15",
        faction:[""],
        pages:"416",
        audio:"15h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 17,
        title: "The Outcast Dead",
        author: "Graham McNeill",
        book:"Book 17",
        faction:[""],
        pages:"416",
        audio:"14h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 18,
        title: "Deliverance Lost",
        author: "",
        book:"Book 18",
        faction:[""],
        pages:"480",
        audio:"16h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 19,
        title: "Know No Fear",
        author: "Dan Abnett",
        book:"Book 19",
        faction:[""],
        pages:"416",
        audio:"11h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 21,
        title: "Fear to Tread",
        author: "James Swallow",
        book:"Book 21",
        faction:[""],
        pages:"516",
        audio:"15h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 23,
        title: "Angel Exterminatus",
        author: "Graham McNeill",
        book:"Book 23",
        faction:[""],
        pages:"448 ",
        audio:"19h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 24,
        title: "Betrayer",
        author: "Aaron Dembski-Bowden",
        book:"Book 24",
        faction:[""],
        pages:"416 ",
        audio:"14h 9m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 26,
        title: "Vulkan Lives",
        author: "Nick Kyme",
        book:"Book 26",
        faction:[""],
        pages:"416",
        audio:"13h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 27,
        title: "The Unremembered Empire",
        author: "",
        book:"Book 27",
        faction:[""],
        pages:"416",
        audio:"13h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 28,
        title: "Scars",
        author: "Chris Wraight",
        book:"Book 28",
        faction:[""],
        pages:"416",
        audio:"11h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 29,
        title: "Vengeful Spirit",
        author: "",
        book:"Book 29",
        faction:[""],
        pages:"544",
        audio:"15h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 30,
        title: "The Damnation of Pythos",
        author: "David Annandale",
        book:"Book 30",
        faction:[""],
        pages:"416",
        audio:"12h",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 32,
        title: "",
        author: "",
        book:"Book 32",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 34,
        title: "Pharos",
        author: "Guy Haley",
        book:"Book 34",
        faction:[""],
        pages:"480",
        audio:"13h 23m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 36,
        title: "The Path of Heaven",
        author: "Chris Wraight",
        book:"Book 36",
        faction:[""],
        pages:"432",
        audio:"13h 28m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 38,
        title: "Angels of Caliban",
        author: "Gav Thorpe",
        book:"Book 38",
        faction:[""],
        pages:"480",
        audio:"10h 57m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 39,
        title: "Praetorian of Dorn",
        author: "John French",
        book:"Book 39",
        faction:[""],
        pages:"478",
        audio:"12h 57m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 40,
        title: "Corax",
        author: "Gav Thorpe",
        book:"Book 40",
        faction:[""],
        pages:"464",
        audio:"12h 49m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 41,
        title: "The Master of Mankind",
        author: "Aaron Dembski-Bowden",
        book:"Book 41",
        faction:[""],
        pages:"448",
        audio:"12h 34m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 42,
        title: "Garro",
        author: "James Swallow",
        book:"Book 42",
        faction:[""],
        pages:"384",
        audio:"12h 27m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 44,
        title: "The Crimson King",
        author: "Graham McNeill",
        book:"Book 44",
        faction:[""],
        pages:"456",
        audio:"14h 46m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 46,
        title: "Ruinstorm",
        author: " 	David Annandale",
        book:"Book 46",
        faction:[""],
        pages:"480",
        audio:"10h 7m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 47,
        title: "Old Earth",
        author: "Nick Kyme",
        book:"Book 47",
        faction:[""],
        pages:"400",
        audio:"12h 38m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 49,
        title: "Wolfsbane",
        author: "Guy Haley",
        book:"Book 49",
        faction:[""],
        pages:"400",
        audio:"11h 36m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 50,
        title: "Born of Flame",
        author: "Nick Kyme",
        book:"Book 50",
        faction:[""],
        pages:"544",
        audio:"15h 54m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 51,
        title: "Slaves to Darkness",
        author: "John French",
        book:"Book 51",
        faction:[""],
        pages:"432",
        audio:"10h 49m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 53,
        title: "Titandeath",
        author: "Guy Haley",
        book:"Book 53",
        faction:[""],
        pages:"480",
        audio:"13h 40m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 54,
        title: "The Buried Dagger",
        author: "James Swallow",
        book:"Book 54",
        faction:[""],
        pages:"400",
        audio:"12h 40m",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 55,
        title: "Grandfather's Gift",
        author: "Guy Haley",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 56,
        title: "The Atonement of Fire",
        author: "David Annandale",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 57,
        title: "A Lesson in Iron",
        author: "David Guymer",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 58,
        title: "Ghost of Nuceria",
        author: "Ian St. Martin",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 59,
        title: "The Passing Of Angels",
        author: "John French",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 60,
        title: "The Abyssal Edge",
        author: "Aaron Dembski-Bowden",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 61,
        title: "Mercy of the Dragon",
        author: "Nick Kyme",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 62,
        title: "The Will of the Legion",
        author: "Andy Clark",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 63,
        title: "Embers of Extinction",
        author: "Brandon Easton",
        book:"Primarchs eBook",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 64,
        title: "Perturabo: Stone and Iron",
        author: "Robbie MacNiven",
        book:"Audio Dramas",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 65,
        title: "Malcador: First Lord of the Imperium",
        author: "L.J. Goulding",
        book:"Audio Dramas",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 66,
        title: "Konrad Curze: A Lesson in Darkness",
        author: "Ian St. Martin",
        book:"Audio Dramas",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 67,
        title: "Illyrium",
        author: "Darius Hinks",
        book:"Audio Dramas",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 68,
        title: "The Revelation of the Word",
        author: "David Annandale",
        book:"Audio Dramas",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 69,
        title: "Morningstar",
        author: "Graham McNeill",
        book:"Audio Dramas",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 70,
        title: "Valdor: Birth of the Imperium",
        author: "Chris Wraight",
        book:"Characters Novels",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 71,
        title: "Luther: First of the Fallen",
        author: "Gav Thorpe",
        book:"Characters Novels",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
    {
        x:1,
        y:1,
        id: 72,
        title: "Sigismund: The Eternal Crusader",
        author: "John French",
        book:"Characters Novels",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
];
export default horusHeresyDataBooks;
/*
    {
        x:1,
        y:1,
        id: 70,
        title: "",
        author: "",
        book:"Characters Novels",
        faction:[""],
        pages:"",
        audio:"",
        rating:"%",
        link: "",
    },
*/


export const horusHeresyDataArrow = [
    {
        id:1,
        color:"red",
        type:"primary",
        dimension:[{x:340,y:150,length:100,height:20},{x:340,y:150,length:20,height:100}]
    },
    {   
        id:2,
        color:"blue",
        type:"secondary",
        dimension:[{x:200,y:100,length:100,height:20}]
    },
    {
        id:3,
        color:"green",
        type:"tertiary",
        dimension:[{x:300,y:100,length:100,height:20}]
    },
];