const imperialGaurdDataBooks = [
    {
        x: 430,
        y: 430,
        id: 1,
        title: "A Ghost Return",
        author: "Dan Abnett",
        book:"Short story",
        faction: [""],
        pages:"",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/quick-reads/A-ghost-return-ebook.html",
        primary: false,
    },
    {
        x: 750,
        y: 550,
        id: 2,
        title: "Ghostmaker Chapter One",
        author: "Dan Abnett",
        book:"Chapter",
        faction: [""],
        pages:"",
        audio:"53m",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/Ghostmaker-eBook.html",
        primary: false,
    },
    {
        x: 1070,
        y: 430,
        id: 3,
        title: "First and Only",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"288",
        audio:"10h",
        rating: "",
        link:"https://www.blacklibrary.com/all-products/first-and-only-20th-anniversary-ed--ebook-2019.html",
        primary: true,
    },
    {
        x: 1400,
        y: 430,
        id: 4,
        title: "Ghostmaker",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"",
        audio:"10h 15m",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/Ghostmaker-eBook.html",
        primary: true,
    },
    {
        x: 1700,
        y: 430,
        id: 5,
        title: "Necropolis",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"10h 24m",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/necropolis-ebook.html",
        primary: true,
    },
    {
        x: 2000,
        y: 430,
        id: 6,
        title: "Honour Guard",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"10h 13m",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/honour-guard-ebook.html",
        primary: true,
    },
    {
        x: 2300,
        y: 430,
        id: 7,
        title: "The Guns of Tanith",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"10h 11m",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/guns-of-tanith-the-ebook.html",
        primary: true,
    },
    {
        x: 2600,
        y: 430,
        id: 8,
        title: "Straight Silve",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"320",
        audio:"9h 52m",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/straight-silver-ebook.html",
        primary: true,
    },
    {
        x: 2900,
        y: 430,
        id: 9,
        title: "Sabbat Martyr",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"319",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/sabbat-martyr-ebook.html",
        primary: true,
    },
    {
        x: 3200,
        y: 700,
        id: 10,
        title: "Double Eagle",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"320 (2004 & 2010 edition) 416 (2005 edition)",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/double-eagle-epub-2019.html",
        primary: false,
    },
    {
        x: 3300,
        y: 430,
        id: 11,
        title: "Traitor General",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/traitor-general-ebook.html",
        primary: true,
    },
    {
        x: 3600,
        y: 430,
        id: 12,
        title: "His Last Command",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/his-last-command-ebook.html",
        primary: true,
    },
    {
        x: 3900,
        y: 416,
        id: 13,
        title: "The Armour of Contempt",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"315",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/Armour-of-Contempt-The-eBook.html",
        primary: true,
    },
    {
        x: 4200,
        y: 430,
        id: 14,
        title: "Only in Death",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"320",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/all-products/only-in-death-ebook.html",
        primary: true,
    },
    {
        x: 4500,
        y: 700,
        id: 15,
        title: "Titanicus",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"	400 (hardcover) 608 (softcover)",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/titanicus-ebook.html",
        primary: false,
    },
    {
        x: 4500,
        y: 430,
        id: 16,
        title: "Blood Pact",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"316",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/blood-pact-ebook.html",
        primary: true,
    },
    {
        x: 4800,
        y: 430,
        id: 17,
        title: "Salvation's Reach",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"320",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/audio/warhammer-40000-audiobooks/salvations-reach-unabridged-audiobook.html",
        primary: true,
    },
    {
        x: 5100,
        y: 700,
        id: 18,
        title: "Volpone Glory",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"466",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/all-products/volpone-glory-ebook-eng-2021.html",
        primary: true,
    },
    {
        x: 5100,
        y: 430,
        id: 19,
        title: "The Warmaster",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"320",
        audio:"14h 17m",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/the-warmaster-ebook.html",
        primary: true,
    },
    {
        x: 5400,
        y: 430,
        id: 20,
        title: "The Anarch",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"400",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/series/gaunts-ghosts/gaunt's-ghosts-the-anarch-ebook.html",
        primary: true,
    },
    {
        x: 5700,
        y: 700,
        id: 21,
        title: "Urdesh: The Serpent and the Saint",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/prod-home/new/urdesh-the-serpent-and-the-saint-ebook-2021.html",
        primary: true,
    },
    {
        x: 6000,
        y: 686,
        id: 22,
        title: "Urdesh: The Magister and the Martyr",
        author: "Dan Abnett",
        book:"Novel",
        faction: [""],
        pages:"",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/all-products/ebook-urdesh-the-magister-and-the-martyr-eng-2021.html",
        primary: true,
    },
    {
        x: 350,
        y: 1130,
        id: 23,
        title: "Cadia Stands",
        author: "Justin D. Hill",
        book:"Novel",
        faction: [""],
        pages:"244",
        audio:"7h 39m",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/cadia-stands-ebook.html",
        primary: true,
    },
    {
        x: 650,
        y: 1130,
        id: 24,
        title: "Cadian Honour",
        author: "Justin D. Hill",
        book:"Novel",
        faction: [""],
        pages:"376",
        audio:"12h 40m",
        rating: "",
        link:"https://www.blacklibrary.com/all-products/advent-2018-26-cadian-honour-ebook.html",
        primary: true,
    },
    {
        x: 950,
        y: 1130,
        id: 25,
        title: "Traitor Rock",
        author: "Justin D. Hill",
        book:"Novel",
        faction: [""],
        pages:"376",
        audio:"9h 45m",
        rating: "",
        link:"https://www.blacklibrary.com/new-titles/featured/traitor-rock-ebook-2021.html",
        primary: true,
    },
    {
        x: 1350,
        y: 1150,
        id: 26,
        title: "Fifteen Hours",
        author: "Mitchel Scanlon",
        book:"Novel",
        faction: [""],
        pages:"256",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/fifteen-hours-ebook.html",
        primary: true,
    },
    {
        x: 1650,
        y: 1150,
        id: 27,
        title: "Death World",
        author: "Steve Lyons",
        book:"Novel",
        faction: [""],
        pages:"256",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/all-products/death-world-ebook.html",
        primary: true,
    },
    {
        x: 1950,
        y: 1150,
        id: 28,
        title: "Rebel Winter",
        author: "Steve Parker",
        book:"Novel",
        faction: [""],
        pages:"256",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/rebel-winter-ebook.html",
        primary: true,
    },
    {
        x: 2250,
        y: 1150,
        id: 29,
        title: "Desert Raiders",
        author: "",
        book:"Novel",
        faction: [""],
        pages:"256",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/desert-raiders-ebook.html",
        primary: true,
    },
    {
        x: 2550,
        y: 1150,
        id: 30,
        title: "Ice Guard",
        author: "Steve Lyons",
        book:"Novel",
        faction: [""],
        pages:"288",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/ice-guard-ebook.html",
        primary: true,
    },
    {
        x: 2850,
        y: 1150,
        id: 31,
        title: "Gunheads",
        author: "Steve Parker",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/gunheads-ebook.html",
        primary: true,
    },
    {
        x: 3150,
        y: 1150,
        id: 32,
        title: "Cadian Blood",
        author: "Aaron Dembski-Bowden",
        book:"Novel",
        faction: [""],
        pages:"320",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/cadian-blood-ebook.html",
        primary: true,
    },
    {
        x: 3450,
        y: 1150,
        id: 33,
        title: "Redemption Corps",
        author: "Rob Sanders",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/redemption-corps-ebook.html",
        primary: true,
    },
    {
        x: 1350,
        y: 1350,
        id: 34,
        title: "Dead Men Walking",
        author: "Steve Lyons",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/Dead-Men-Walking-eBook.html",
        primary: true,
    },
    {
        x: 1650,
        y: 1350,
        id: 35,
        title: "Imperial Glory",
        author: "Richard Williams",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/imperial-glory-ebook.html",
        primary: true,
    },
    {
        x: 1950,
        y: 1350,
        id: 36,
        title: "Iron Guard",
        author: "Mark Clapham",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/iron-guard-ebook.html",
        primary: true,
    },
    {
        x: 2250,
        y: 1350,
        id: 37,
        title: "Commissar",
        author: "Andy Hoare",
        book:"Novel",
        faction: [""],
        pages:"416",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/commissar-ebook.html",
        primary: true,
    }, 
    {
        x: 2550,
        y: 1350,
        id: 38,
        title: "Straken",
        author: "Toby Frost",
        book:"Novel",
        faction: [""],
        pages:"320",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/straken-ebook.html",
        primary: true,
    },
    {
        x: 2850,
        y: 1350,
        id: 39,
        title: "Baneblade",
        author: "Guy Haley",
        book:"Novel",
        faction: [""],
        pages:"415",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/warhammer-40000/novels/baneblade-ebook.html",
        primary: true,
    },
    {
        x: 3150,
        y: 1350,
        id: 40,
        title: "Shadowsword",
        author: "Guy Haley",
        book:"Novel",
        faction: [""],
        pages:"384",
        audio:"",
        rating: "",
        link:"https://www.blacklibrary.com/all-products/shadowsword-ebook.html",
        primary: true,
    },
];
export default imperialGaurdDataBooks;


export const imperialGaurdDataArrow = [
    {
        id:1,
        type:"secondary",
        start:1,
        end:2,
    },
    {   
        id:2,
        type:"secondary",
        start:2,
        end:3,
    },
    {
        id:3,
        type:"primary",
        start:3,
        end:4,
    },
    {
        id:4,
        type:"primary",
        start:1,
        end:3,
    },
    {
        id:5,
        type:"primary",
        start:4,
        end:5,
    },
    {
        id:6,
        type:"primary",
        start:5,
        end:6,
    },
    {
        id:7,
        type:"primary",
        start:6,
        end:7,
    },
    {
        id:8,
        type:"primary",
        start:7,
        end:8,
    },
    {
        id:9,
        type:"primary",
        start:8,
        end:9,
    },
    {
        id:10,
        type:"primary",
        start:9,
        end:11,
    },
    {
        id:11,
        type:"secondary",
        start:9,
        end:10,
    },
    {
        id:12,
        type:"primary",
        start:11,
        end:12,
    },
    {
        id:13,
        type:"primary",
        start:12,
        end:13,
    },
    {
        id:14,
        type:"secondary",
        start:14,
        end:15,
    },
    {
        id:15,
        type:"primary",
        start:14,
        end:16,
    },
    {
        id:16,
        type:"primary",
        start:16,
        end:17,
    },
    {
        id:17,
        type:"secondary",
        start:17,
        end:18,
    },
    {
        id:18,
        type:"primary",
        start:19,
        end:20,
    },
    {
        id:19,
        type:"secondary",
        start:20,
        end:21,
    },
    {
        id:20,
        type:"primary",
        start:17,
        end:19,
    },
    {
        id:21,
        type:"secondary",
        start:21,
        end:22,
    },
    {
        id:22,
        type:"primary",
        start:13,
        end:14,
    },
    {
        id:23,
        type:"primary",
        start:23,
        end:24,
    },
    {
        id:24,
        type:"primary",
        start:24,
        end:25,
    },
    {
        id:25,
        type:"primary",
        start:39,
        end:40,
    },
]

export const imperialGaurdDataZone = [
    {
        x:300,
        y:290,
        width:6000,
        height:630,
        xtitle:50,
        ytitle:40,
        id:1,
        title:"Gaunt's Ghosts and the history of the Sabbat Worlds Crusade",
    },
    {
        x:300,
        y:1000,
        width:950,
        height:320,
        xtitle:50,
        ytitle:40,
        id:2,
        title:"Cadia",
    },
    {
        x:1300,
        y:1000,
        width:2440,
        height:550,
        xtitle:50,
        ytitle:40,
        id:3,
        title:"Imperial Guard Novel Series",
    },
]